<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bruno Sanchez-Andrade Nuno">
<meta name="dcterms.date" content="2026-04-22">
<meta name="description" content="This post shows that Clay embeddings do contain semantic information like location, size, orientation, and count. And the mechanism to scale this retrieval to planetary scale, without agents or reading pixels.">

<title>Cheaper than a pixel, faster than an agent; the geoembedding knows more than you think – Lgnd.ai — Devlogs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c3ab6e2df469e894a5aed8e5b798b760.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Cheaper than a pixel, faster than an agent; the geoembedding knows more than you think – Lgnd.ai — Devlogs">
<meta property="og:description" content="This post shows that Clay embeddings do contain semantic information like location, size, orientation, and count. And the mechanism to scale this retrieval to planetary scale, without agents or reading pixels.">
<meta property="og:image" content="https://devlogs.lgnd.ai/posts/2026-04-22-geometric-probing-clay/assets/boat1_native_4b.jpg">
<meta property="og:site_name" content="Lgnd.ai — Devlogs">
<meta name="twitter:title" content="Cheaper than a pixel, faster than an agent; the geoembedding knows more than you think – Lgnd.ai — Devlogs">
<meta name="twitter:description" content="This post shows that Clay embeddings do contain semantic information like location, size, orientation, and count. And the mechanism to scale this retrieval to planetary scale, without agents or reading pixels.">
<meta name="twitter:image" content="https://devlogs.lgnd.ai/posts/2026-04-22-geometric-probing-clay/assets/boat1_native_4b.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Lgnd.ai — Devlogs</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EarthLegend"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#agents-pixels-or-images" id="toc-agents-pixels-or-images" class="nav-link active" data-scroll-target="#agents-pixels-or-images">Agents, pixels or images</a></li>
  <li><a href="#cosine-is-blind-to-binding" id="toc-cosine-is-blind-to-binding" class="nav-link" data-scroll-target="#cosine-is-blind-to-binding">Cosine is Blind to Binding</a></li>
  <li><a href="#the-thesis-cheaper-than-a-pixel-faster-than-an-agent" id="toc-the-thesis-cheaper-than-a-pixel-faster-than-an-agent" class="nav-link" data-scroll-target="#the-thesis-cheaper-than-a-pixel-faster-than-an-agent">The Thesis: Cheaper than a pixel, faster than an agent</a></li>
  <li><a href="#widget" id="toc-widget" class="nav-link" data-scroll-target="#widget">Try it Yourself: The 1µs Readout</a></li>
  <li><a href="#the-case-from-pixels-to-primitives" id="toc-the-case-from-pixels-to-primitives" class="nav-link" data-scroll-target="#the-case-from-pixels-to-primitives">The Case: From Pixels to Primitives</a></li>
  <li><a href="#tldr-the-findings-grouped-by-value" id="toc-tldr-the-findings-grouped-by-value" class="nav-link" data-scroll-target="#tldr-the-findings-grouped-by-value">TL;DR The Findings: Grouped by Value</a>
  <ul class="collapse">
  <li><a href="#cosine-accessible-properties" id="toc-cosine-accessible-properties" class="nav-link" data-scroll-target="#cosine-accessible-properties">Cosine-accessible properties</a></li>
  <li><a href="#probe-accesible-properties" id="toc-probe-accesible-properties" class="nav-link" data-scroll-target="#probe-accesible-properties">Probe-accesible properties</a></li>
  <li><a href="#agent-only-properties" id="toc-agent-only-properties" class="nav-link" data-scroll-target="#agent-only-properties">Agent-only properties</a></li>
  </ul></li>
  <li><a href="#dimensions-are-enough-for-some-properties" id="toc-dimensions-are-enough-for-some-properties" class="nav-link" data-scroll-target="#dimensions-are-enough-for-some-properties">64 Dimensions are enough for some properties</a></li>
  <li><a href="#the-operational-playbook" id="toc-the-operational-playbook" class="nav-link" data-scroll-target="#the-operational-playbook">The Operational Playbook</a></li>
  <li><a href="#appendix-methods-caveats" id="toc-appendix-methods-caveats" class="nav-link" data-scroll-target="#appendix-methods-caveats">Appendix: Methods &amp; Caveats</a>
  <ul class="collapse">
  <li><a href="#lobo-spread" id="toc-lobo-spread" class="nav-link" data-scroll-target="#lobo-spread">LOBO spread</a></li>
  <li><a href="#per-probe-hull-matrix-where-cosine-and-probe-disagree-per-hull" id="toc-per-probe-hull-matrix-where-cosine-and-probe-disagree-per-hull" class="nav-link" data-scroll-target="#per-probe-hull-matrix-where-cosine-and-probe-disagree-per-hull">Per-(probe × hull) matrix — where cosine and probe disagree per hull</a></li>
  <li><a href="#how-distinct-are-the-8-hulls-really" id="toc-how-distinct-are-the-8-hulls-really" class="nav-link" data-scroll-target="#how-distinct-are-the-8-hulls-really">How Distinct Are the 8 Hulls Really?</a></li>
  <li><a href="#detailed-stats-table" id="toc-detailed-stats-table" class="nav-link" data-scroll-target="#detailed-stats-table">Detailed Stats Table</a></li>
  <li><a href="#reproduce" id="toc-reproduce" class="nav-link" data-scroll-target="#reproduce">Reproduce</a></li>
  </ul></li>
  <li><a href="#prior-art" id="toc-prior-art" class="nav-link" data-scroll-target="#prior-art">Prior Art</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/EarthLegend/devlogs/edit/main/posts/2026-04-22-geometric-probing-clay/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/EarthLegend/devlogs/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Cheaper than a pixel, faster than an agent; the geoembedding knows more than you think</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Clay embeddings do contain semantic information like location, size, orientation, and count of semantics within the image. Readable with linear probes.</p>
  <div class="quarto-categories">
    <div class="quarto-category">embeddings</div>
    <div class="quarto-category">foundation-models</div>
    <div class="quarto-category">clay</div>
    <div class="quarto-category">probing</div>
  </div>
  </div>

<div>
  <div class="description">
    This post shows that Clay embeddings do contain semantic information like location, size, orientation, and count. And the mechanism to scale this retrieval to planetary scale, without agents or reading pixels.
  </div>
</div>


<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bruno Sanchez-Andrade Nuno </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="agents-pixels-or-images" class="level2">
<h2 class="anchored" data-anchor-id="agents-pixels-or-images">Agents, pixels or images</h2>
<p>GeoAI is proving to be a powerful tool for understanding the Earth. There are three main pillars of this progress: agents to orchestrate complex reasoning, pull pixels, and iterate towards results; geo-embeddings for each pixel, where we convert patterns of raw radiance into universal indices of semantics; and geo-embeddings of patches of pixels like 256×256 “chips” all at once to create a single embedding for the whole scene. Agents are hard to scale globally since they scale with usage. Pixel embeddings are efficient semantic compressions but one-per-pixel scales poorly, especially when we want high spatial and temporal resolution. Chip embeddings are a middle ground — orders of magnitude less volume, and allowing grids of tiles — but they have typically been considered unable to efficiently translate that “semantic within” into <em>where</em> exactly or <em>what</em> properties.</p>
<p>The goal of this post is to take a simple case of boats on water and see if we can use chip embeddings to retrieve where they are in the image, their orientation, their size, and their count. Not only do we prove that the information is there, but we also show how to retrieve it with a simple linear probe — orders of magnitude cheaper than an agent.</p>
<p>We believe this is a critical piece to more efficiently orchestrate agents, pixel embeddings, and chip embeddings. To the degree we can extract semantic properties through these probes, they become the <strong>think-fast</strong> mode under any agentic flow: used as first-pass filters, retrieval cues, or rerankers that decide which candidates the expensive agent, pixel embeddings, or pixel CV should look at.</p>
</section>
<section id="cosine-is-blind-to-binding" class="level2">
<h2 class="anchored" data-anchor-id="cosine-is-blind-to-binding">Cosine is Blind to Binding</h2>
<p>In any standard vector database using <strong>cosine similarity</strong> on Clay v1.5 embeddings, these two chips — <code>boat1@TOP+boat2@BOT</code> and <code>boat1@BOT+boat2@TOP</code> — are <strong>99.93% identical</strong>. To a retrieval engine, they are the same scene. If you re-rendered Chip A with different water noise, it would actually look <em>more</em> different (cosine 0.9986) than the swap. <strong>Standard vector search is blind to the bound arrangement of content.</strong> Yet, a <strong>1µs linear probe</strong> — a single dot product on the same 1024-D vector — distinguishes the swap at <strong>0.87 accuracy</strong> (permutation p &lt; 0.005, i.e.&nbsp;fewer than 1 in 200 random label-shuffles match the trained probe’s score). This proves that the embedding knows far more about the image it encodes.</p>
</section>
<section id="the-thesis-cheaper-than-a-pixel-faster-than-an-agent" class="level2">
<h2 class="anchored" data-anchor-id="the-thesis-cheaper-than-a-pixel-faster-than-an-agent">The Thesis: Cheaper than a pixel, faster than an agent</h2>
<p>Every time we ask a question — <em>“Is this tanker pointed North?”</em> or <em>“Are there more than three boats here?”</em> — an agentic approach pays a tax in tokens and seconds to re-process pixels; a pixel-embedding approach pays a tax in storage and retrieval time to read from a separate index; and a custom-CV approach pays the tax of pulling the pixels and running a model on the chip.</p>
<p>But for the billions of chips already indexed by LGND, we discovered that that “reasoning” has already happened. It’s sitting inside the 1024-D CLS embedding one linear probe away from being read — a dot product, ~1µs on a CPU.</p>
</section>
<section id="widget" class="level2">
<h2 class="anchored" data-anchor-id="widget">Try it Yourself: The 1µs Readout</h2>
<p>Pick a hull state. The readout below shows what each linear probe “reads” from Clay’s CLS for that exact chip. Watch the <em>probe</em> readings as you change one slider — this is the embedding’s internal geometry being decoded in real-time.</p>
<style>
  #pw4 { background:#0e0e12; color:#f0f0f0; padding:18px 16px; border-radius:8px; font-family: ui-sans-serif,system-ui,sans-serif; margin:1.5em 0; max-width:760px; }
  #pw4 .row { display:grid; grid-template-columns: 256px 1fr; gap:20px; align-items:flex-start; }
  @media (max-width: 600px) { #pw4 .row { grid-template-columns: 1fr; } }
  #pw4 img, #pw4 canvas { width:100%; max-width:256px; aspect-ratio:1/1; border:1px solid #2a2a32; image-rendering:pixelated; background:#000; display:block; }
  #pw4 .controls > * { margin-bottom:10px; }
  #pw4 .axisrow { display:grid; grid-template-columns: 70px 1fr 90px; gap:10px; align-items:center; }
  #pw4 .axislbl { color:#4aa0ff; font-weight:600; font-size:13px; }
  #pw4 .axislvl { color:#f0f0f0; font-size:13px; font-weight:600; text-align:right; }
  #pw4 .controls input[type=range] { width:100%; }
  #pw4 .reads { background:#15151c; border:1px solid #2a2a32; border-radius:6px; padding:8px 12px; font-size:12px; line-height:1.6; margin-top:6px; }
  #pw4 .reading { display:grid; grid-template-columns: 80px 1fr 1fr; gap:8px; padding:4px 0; align-items:center; }
  #pw4 .reading + .reading { border-top:1px solid #2a2a32; }
  #pw4 .reading .axis { color:#a0a0a8; font-size:11px; }
  #pw4 code { background:#26262e; color:#dde; padding:1px 5px; border-radius:3px; font-size:11px; }
  #pw4 .ok { color:#00dc78; }
  #pw4 .miss { color:#ffcc33; }
  #pw4 .none { color:#888; font-style:italic; }
  #pw4 .stats { color:#a0a0a8; font-size:11px; margin-top:8px; line-height:1.55; }
  #pw4 .footnote { color:#a0a0a8; font-size:11px; margin-top:12px; }
  #pw4 .nomatch { color:#ffcc33; font-size:12px; margin-top:6px; }
</style>

<div id="pw4">
  <div class="row">
    <div>
      <canvas id="pw4Chip" width="256" height="256" aria-label="composite chip painted live in the browser"></canvas>
      <div class="nomatch" id="pw4NoMatch"></div>
    </div>
    <div class="controls">
      <div class="axisrow">
        <div class="axislbl">Size</div>
        <input id="pw4Size" type="range" min="0" step="1" value="1">
        <div class="axislvl" id="pw4SizeLvl">—</div>
      </div>
      <div class="axisrow">
        <div class="axislbl">Count</div>
        <input id="pw4Count" type="range" min="0" step="1" value="1">
        <div class="axislvl" id="pw4CountLvl">—</div>
      </div>
      <div class="axisrow">
        <div class="axislbl">Position</div>
        <input id="pw4Pos" type="range" min="0" step="1" value="4">
        <div class="axislvl" id="pw4PosLvl">—</div>
      </div>
      <div class="axisrow">
        <div class="axislbl">Rotation</div>
        <input id="pw4Rot" type="range" min="0" step="1" value="0">
        <div class="axislvl" id="pw4RotLvl">—</div>
      </div>
      <div class="reads" id="pw4Reads">…</div>
      <div class="stats" id="pw4Stats"></div>
    </div>
  </div>
  <div class="footnote">All chips are composites of real 4-band NAIP vessel cutouts onto water. Predictions shown are from linear probes on the 1024-D CLS vector.</div>
</div>

<script>
(function () {
  const root = document.getElementById('pw4');
  if (!root) return;
  const CHIP = 256;
  const POS9 = {
    top_left:    [0.20, 0.20], top:    [0.50, 0.20], top_right:    [0.80, 0.20],
    left:        [0.20, 0.50], center: [0.50, 0.50], right:        [0.80, 0.50],
    bottom_left: [0.20, 0.80], bottom: [0.50, 0.80], bottom_right: [0.80, 0.80],
  };
  const HULL = 'boat_06';
  const HULL_FILE = 'canonical_boat_06_4b_preview.png';
  const WATER_FILE = 'water_native_4b.jpg';
  const fmtPos = v => v ? v.replace(/_/g, ' ') : '—';
  const fmtHull = h => h ? h.replace(/^boat_?/, 'b') : '—';
  function loadImg(src) {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error('failed to load ' + src));
      img.src = src;
    });
  }
  Promise.all([
    fetch('assets/widget_data_4b.json').then(r => r.json()),
    loadImg('assets/' + WATER_FILE),
    loadImg('assets/' + HULL_FILE),
  ]).then(([d, water, hullImg]) => {
    const chips = d.chips;
    const canvas = root.querySelector('#pw4Chip');
    const ctx = canvas.getContext('2d');
    const sliders = {
      size:     { el: root.querySelector('#pw4Size'),  lvl: root.querySelector('#pw4SizeLvl'),
                  levels: d.axes.size.levels,     fmt: v => v.toFixed(2),       idx: 1 },
      count:    { el: root.querySelector('#pw4Count'), lvl: root.querySelector('#pw4CountLvl'),
                  levels: d.axes.count.levels,    fmt: v => 'N = ' + v,         idx: 1 },
      position: { el: root.querySelector('#pw4Pos'),   lvl: root.querySelector('#pw4PosLvl'),
                  levels: d.axes.position.levels, fmt: v => fmtPos(v),          idx: 4 },
      rotation: { el: root.querySelector('#pw4Rot'),   lvl: root.querySelector('#pw4RotLvl'),
                  levels: d.axes.rotation.levels, fmt: v => v + '°',            idx: 0 },
    };
    Object.values(sliders).forEach(s => {
      s.el.max = s.levels.length - 1;
      s.el.value = s.idx;
      s.el.addEventListener('input', e => { s.idx = parseInt(e.target.value, 10); update(); });
    });
    function placements(count, cx, cy) {
      if (count <= 1) return [[cx, cy]];
      const offsets = [[0, 0], [-55, -35], [55, -35], [-55, 35], [55, 35],
                       [0, -65], [0, 65], [-75, 0], [75, 0]];
      const out = [];
      for (let i = 0; i < count && i < offsets.length; i++) {
        const [dx, dy] = offsets[i];
        out.push([
          Math.max(36, Math.min(CHIP - 36, cx + dx)),
          Math.max(36, Math.min(CHIP - 36, cy + dy)),
        ]);
      }
      return out;
    }
    function paint(size, count, position, rotation) {
      ctx.drawImage(water, 0, 0, CHIP, CHIP, 0, 0, CHIP, CHIP);
      if (count === 0) return;
      const longest = Math.max(hullImg.width, hullImg.height);
      const targetLong = Math.max(4, Math.round(size * CHIP));
      const ratio = targetLong / longest;
      const w = hullImg.width * ratio, h = hullImg.height * ratio;
      const [fx, fy] = POS9[position] || [0.5, 0.5];
      const cx = fx * CHIP, cy = fy * CHIP;
      const rad = (rotation || 0) * Math.PI / 180;
      for (const [px, py] of placements(count, cx, cy)) {
        ctx.save();
        ctx.translate(px, py);
        ctx.rotate(rad);
        ctx.drawImage(hullImg, -w / 2, -h / 2, w, h);
        ctx.restore();
      }
    }
    function findExactMatch(size, count, position, rotation) {
      if (count === 0) {
        return chips.find(c => c.is_null && c.source_id === 'null_water')
            || chips.find(c => c.is_null);
      }
      return chips.find(c => c.hull === HULL && c.size === size
                           && c.count === count && c.position === position
                           && c.rotation === rotation);
    }
    function ok(axis, gt, pred) {
      if (gt === null || gt === undefined) return null;
      if (pred === null || pred === undefined) return null;
      if (axis === 'size')     return Math.abs(gt - pred) <= 0.15;
      if (axis === 'count')    return Math.abs(gt - pred) <= 1.0;
      if (axis === 'rotation') {
        const dr = ((gt - pred + 540) % 360) - 180;
        return Math.abs(dr) <= 45;
      }
      return String(gt) === String(pred);
    }
    function fmtVal(axis, v) {
      if (v === null || v === undefined) return '—';
      if (axis === 'size')     return Number(v).toFixed(2);
      if (axis === 'count')    return Number(v).toFixed(1);
      if (axis === 'rotation') return Math.round(Number(v)) + '°';
      if (axis === 'position') return fmtPos(v);
      if (axis === 'hull')     return fmtHull(v);
      return String(v);
    }
    function update() {
      const size = sliders.size.levels[sliders.size.idx];
      const count = sliders.count.levels[sliders.count.idx];
      const position = sliders.position.levels[sliders.position.idx];
      const rotation = sliders.rotation.levels[sliders.rotation.idx];
      Object.entries(sliders).forEach(([k, s]) => { s.lvl.textContent = s.fmt(s.levels[s.idx]); });
      paint(size, count, position, rotation);
      const chip = findExactMatch(size, count, position, rotation);
      const order = ['size','count','position','rotation'];
      if (chip) {
        root.querySelector('#pw4NoMatch').textContent = '';
        const rows = order.map(name => {
          const gt = chip.gt[name];
          const pred = chip.pred[name];
          const hit = ok(name, gt, pred);
          const cls = hit === null ? 'none' : (hit ? 'ok' : 'miss');
          const mark = hit === null ? '' : (hit ? '✓' : '✗');
          const Cap = name.charAt(0).toUpperCase() + name.slice(1);
          return '<div class="reading">' +
                   '<div class="axis">' + Cap + '</div>' +
                   '<div>truth <code>' + fmtVal(name, gt) + '</code></div>' +
                   '<div>probe <code class="' + cls + '">' + fmtVal(name, pred) + '</code> ' + mark + '</div>' +
                 '</div>';
        });
        root.querySelector('#pw4Reads').innerHTML = rows.join('');
      } else {
        root.querySelector('#pw4NoMatch').textContent = 'No measured embedding for this exact slider state — chip is painted on the fly. Move sliders to a measured combo to see probe predictions.';
        const rows = order.map(name => {
          const Cap = name.charAt(0).toUpperCase() + name.slice(1);
          return '<div class="reading">' +
                   '<div class="axis">' + Cap + '</div>' +
                   '<div>truth <code>—</code></div>' +
                   '<div>probe <code class="none">—</code></div>' +
                 '</div>';
        });
        root.querySelector('#pw4Reads').innerHTML = rows.join('');
      }
      const headline = order.map(k => `${k} <code>${d.axes[k].within_object_5fold}</code>`).join(', ');
      const lobo = order.map(k => `${k} <code>${d.axes[k].cross_hull_lobo}</code>`).join(', ');
      root.querySelector('#pw4Stats').innerHTML =
        'Within-object 5-fold: ' + headline + '. Cross-hull LOBO: ' + lobo + '.';
    }
    update();
  }).catch(e => {
    root.innerHTML = 'Widget assets failed to load.';
  });
})();
</script>
</section>
<section id="the-case-from-pixels-to-primitives" class="level2">
<h2 class="anchored" data-anchor-id="the-case-from-pixels-to-primitives">The Case: From Pixels to Primitives</h2>
<p>To prove what the embedding knows, we built a controlled path from raw imagery to extracted signals.</p>
<ol type="1">
<li><strong>Raw Image:</strong> We started with wide 4-band NAIP tiles of an SF Bay coastal anchorage.</li>
<li><strong>Canonical Extraction:</strong> Using NIR+LAB signals, we hand-digitized 8 real vessel hulls in QGIS, straightened them to a horizontal principal axis, and saved them as 5-channel alpha cutouts (RGBN+A). We also extracted empty water as a semantically “flat” background.</li>
<li><strong>Factorial Synthetic Samples:</strong> We wanted to study combinations of ship rotation, location in the chip, size, and number of ships (same or different hull mix), including null sets with no boats or white noise as background. The full combinatorial space exceeds <strong>17,000 unique chips</strong> (8 hulls × 5 sizes × 6 counts × 9 positions × 8 rotations), so we sampled an exploratory random grid of <strong>1,042 chips</strong>.</li>
<li><strong>Embedding and Probing:</strong> Every chip was then embedded with the production Clay v1.5 encoder. We trained linear probes (Ridge or LinearSVC) to test if we could “read” these factors back off the frozen vector.</li>
</ol>
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_canonicals_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Figure 1 — The Setup. Top: 8 hand-digitized hulls (RGB). Bottom: The same hulls in native NIR. Clay sees both. These are the “words” in the Dictionary of the Earth.
</figcaption>
</figure>
</div>
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_perturb_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Figure 2 — The Samples. 32 random samples (seed=7) drawn from the 1,042-chip dataset. Every probe in this post trains and tests on draws from this distribution — different hulls, scales, rotations, positions, cardinalities, plus null variants.
</figcaption>
</figure>
</div>
<p><strong>Envelope of validity.</strong> All 8 hulls come from the same coastal anchorage, similar size class (~10–25 m), composited onto a real 4-band water tile from the same source. The 8 canonical hulls sit at off-diagonal cosine <strong>0.97</strong> in embedding space — they’re geometrically distinct but live in a <em>tight</em> neighbourhood of the manifold. Read every LOBO number below as “generalisation within this neighbourhood”, not “generalisation across vessel families”. Cross-anchorage, cross-vessel-class, cross-sensor, and leave-one-water-out replications are open follow-ups, not claims of this post.</p>
<p><strong>A note on what these probes actually test.</strong> Every probe in this post is a categorical or scalar linear readout on specific labels. The 4-class rotation probe is <em>literally</em> a “which-of-N/E/S/W?” classifier; the 8-bin extends to obliques; the continuous-rotation regression generalises further. The position probe is a “which-of-9-grid-cells?” classifier on chip-relative paste position. A high score means <em>this categorical or scalar distinction is linearly decodable from the CLS token across hulls</em> — not “Clay represents X in general”. Where probes fail, they’re failing this narrow test; the embedding may still encode the property non-linearly or in patch tokens.</p>
<p><strong>Are the composites on-manifold?</strong> A reasonable concern with paste-on-water composites is that they might sit in an out-of-distribution corner of the embedding manifold — a probe could then be reading “this is a composite” rather than the geometric factor we’re labelling. Our companion devlog on <strong><a href="../2026-03-01-self-aware-embeddings/">ELLE — self-aware embeddings</a></strong> trained a small head that predicts Clay’s reconstruction loss directly from the CLS. Re-applied to this 4-band 8-hull build, ELLE confirms that composite chips of this kind sit <em>0.8–1.0σ below</em> the typical-NAIP difficulty distribution — inside Clay’s natural manifold, slightly <em>easier</em> than the average NAIP chip Clay was trained on. Gaussian-noise nulls land at +0.73σ — distinctly off-manifold. ELLE separates the two cleanly.</p>
</section>
<section id="tldr-the-findings-grouped-by-value" class="level2">
<h2 class="anchored" data-anchor-id="tldr-the-findings-grouped-by-value">TL;DR The Findings: Grouped by Value</h2>
<p>We measured six primitives. We tested both <strong>5-fold within-object</strong> (leaving 20% of chips out for validation each fold; the same hulls appear in train and test — optimistic upper bound) and <strong>LOBO (Leave-One-Boat-Out)</strong> — train on 7 hulls, test on the 8th, repeated for each. n=8 hulls is not a big sample, but the goal is to check if the signal is there at all and to surface per-hull failure modes via the spread.</p>
<p>Since our goal is maximum retrieval efficiency, we restrict ourselves to the cheapest approach: cosine similarity (which would enable the easiest retrieval), and linear probes under LOBO. No MLPs, no fine-tuning, no agents.</p>
<section id="cosine-accessible-properties" class="level3">
<h3 class="anchored" data-anchor-id="cosine-accessible-properties">Cosine-accessible properties</h3>
<p><strong>Scale (R² 0.94 LOBO)</strong> and <strong>Count (R² 0.84 LOBO)</strong> are the strongest and easiest signals to retrieve — both cosine similarity in-class and LOBO.</p>
<div id="fig-pair-cosine" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pair-cosine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_pair_cosine_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pair-cosine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Cosine-accessible — Scale and Count under LOBO. Each panel shows the per-hull spread (8 dots) plus the mean for cosine top-5 NN (blue) and the linear probe (orange). Both readouts work; cosine is slightly tighter on these two scalar properties because the target value tracks the dominant cosine axis. Dashed line is the within-object 5-fold ceiling.
</figcaption>
</figure>
</div>
<p>The reason cosine works here is mechanically simple: same-scale chips cluster together in cosine space, so top-K nearest-neighbour voting recovers the value. The figure below makes that concrete — at scale 0.25 the top-5 cosine neighbours are near-duplicates (cos ≥ 0.999); at scale 1.0 the top-5 stay at scale 1.0 (smaller variants of the same hull are absent). Cosine is <em>scale-biased</em> — it returns “is this the same scene?” not “is this the same hull at a different size?” — and for the scale-detection question, that bias is a feature, not a bug.</p>
<div id="fig-retrieval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-retrieval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_retrieval_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-retrieval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Top-5 cosine neighbours of canonical hulls at two scales. <strong>Top two rows:</strong> boat1 and boat_05 at scale 0.25 — neighbours are near-duplicates (cos ≥ 0.999). <strong>Bottom two rows:</strong> the same hulls at scale 1.0 — neighbours stay at scale 1.0; smaller variants of the same hull are absent. Cosine retrieval clusters by scale; the linear probe supplies what cosine drops only for properties orthogonal to that clustering.
</figcaption>
</figure>
</div>
</section>
<section id="probe-accesible-properties" class="level3">
<h3 class="anchored" data-anchor-id="probe-accesible-properties">Probe-accesible properties</h3>
<p><strong>Rotation (0.76 acc LOBO)</strong> and <strong>Binding (0.87 acc)</strong> are where cosine retrieval collapses. * <strong>Rotation:</strong> A probe can sort N from S reliably across hulls (39° angular MAE); cosine retrieval is 26% less accurate here. * <strong>Binding (i.e.&nbsp;content × position):</strong> As shown in the “Boat Swap” case, standard vector search sits at chance (0.50), while a probe hits 0.87.</p>
<div id="fig-pair-probe" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pair-probe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_pair_probe_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pair-probe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Probe-accessible — Rotation and Binding under LOBO. <strong>Rotation 4-cls (left):</strong> cosine top-5 NN sits at 0.50 across all 8 hulls; the linear probe lifts it to 0.76 (one outlier — boat_07 at 0.30). <strong>Binding (right):</strong> cos(SWAP)=0.9993 ≈ cos(noise)=0.9986 — cosine cannot tell <code>boat1@TOP+boat2@BOT</code> apart from the same scene re-noised, so on the binding <em>task</em> it sits at chance (0.50). The probe hits 0.87 (perm shuffle mean 0.52, perm-p &lt; 0.005). The discriminating direction is in the embedding, just orthogonal to the dominant cosine axis.
</figcaption>
</figure>
</div>
<p><strong>Rotation, three nested probes.</strong> The 4-class compass classifier is the easiest version (chance 0.25); the 8-bin extends to obliques (chance 0.125); the continuous-rotation regression generalises to any angle. The three give a coarse-to-fine view of how the embedding represents heading.</p>
<ul>
<li><strong>4-cls</strong> (n=448): within-object 0.94, LOBO 0.76 [0.60, 0.90]. boat_07 drops to 0.30.</li>
<li><strong>8-bin</strong> (n=608): within-object 0.93, LOBO 0.80 [0.71, 0.88].</li>
<li><strong>Continuous</strong> (sin/cos Ridge, n=608): within-object <strong>17.8° MAE / 6.9° median</strong>, LOBO <strong>39.5° MAE</strong> with worst hull (boat_08) at 66.8°.</li>
</ul>
<p>The continuous LOBO MAE is the most operationally honest number. It says: the embedding gives you a heading prior accurate to ~one octant on hulls it has never seen — coarse, not fine. The 4-class and 8-bin accuracies are higher because they bucket the angle, hiding the fine-grained miss.</p>
<div id="fig-rotcont" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rotcont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_rotcont_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rotcont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Continuous rotation regression. Left: angular MAE within-object vs LOBO. Right: per-hull LOBO MAE. boat_07 and boat_08 sit far above the mean — the rotation primitive is coarse, not smooth, on held-out hulls.
</figcaption>
</figure>
</div>
</section>
<section id="agent-only-properties" class="level3">
<h3 class="anchored" data-anchor-id="agent-only-properties">Agent-only properties</h3>
<p><strong>Position (0.24 acc LOBO)</strong> and <strong>Per-instance Addressing</strong> fail at the CLS level.</p>
<ul>
<li>The embedding “knows” where a hull is if it has seen it before (0.89 within-object), but it doesn’t generalize that knowledge linearly to new hulls.</li>
<li>For sub-chip localization or pixel-precise damage assessment, the agent <em>has</em> to look at the patches or the pixels. This is the SPEC for when to call the slow-thinker.</li>
</ul>
<p><strong>Three reference lines used in the figure below.</strong> Most polygon-retrieval figures benchmark the probe against three references; we’ll define them once here:</p>
<ul>
<li><strong>Mean-mask baseline.</strong> For each fold, predict the <em>training-set mean alpha mask</em> for every test chip — same prediction for everyone. This is the position-blind null any chip-level probe must beat to demonstrate it carries actual chip-specific spatial signal.</li>
<li><strong>Soft IoU.</strong> Per chip, <code>intersection / union</code> where <code>intersection = sum(min(pred, gt))</code> and <code>union = sum(max(pred, gt))</code> over the 1024 cells of the 32×32 mask grid — both pred and gt continuous in [0, 1]. Soft IoU is bounded in [0, 1] and reduces to standard IoU when both are binary.</li>
<li><strong>Union-oracle ceiling.</strong> For a “find leftmost boat among N” task, the union of <em>all</em> N boats’ masks is the upper bound for any readout that knows <em>where boats are</em> but cannot tell <em>which one is leftmost</em>. Scored against the leftmost-only target, this oracle caps at <strong>1/N</strong> (since at most 1 of N union-cells corresponds to the correct instance). Reaching the oracle means the readout is doing as well as a hull-aware-but-instance-blind detector could; staying below it means the readout is also missing the “where boats are” signal.</li>
</ul>
<div id="fig-pair-agent" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pair-agent-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_pair_agent_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pair-agent-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Agent-only — Position and Per-instance Addressing both fail. <strong>Position 9-cls (left):</strong> cosine 0.27 and probe 0.24 sit essentially at the 1/9 chance line; the within-object 0.89 ceiling (dashed) does not transfer across hulls. <strong>Per-instance addressing (right):</strong> the ridge probe lifts above the mean-mask baseline at every N, but <strong>caps at the union-oracle ceiling</strong> (1/N) — a CLS-level readout cannot pick out <em>which</em> of N boats the question is about. At N=2 the probe captures 26% IoU vs the leftmost target when an instance-aware readout could reach 50%. The CLS doesn’t expose addressable instance slots.
</figcaption>
</figure>
</div>
<section id="polygon-retrieval-silhouette-is-partly-there-but-instance-blind" class="level4">
<h4 class="anchored" data-anchor-id="polygon-retrieval-silhouette-is-partly-there-but-instance-blind">Polygon retrieval — silhouette is <em>partly</em> there, but instance-blind</h4>
<p>We also asked the harder question: can the CLS predict the chip’s <strong>per-cell mask</strong> at 32×32 (matching Clay’s patch grid)? A multi-output Ridge per fold; soft-IoU vs the ground-truth alpha mask.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Stratum</th>
<th>n</th>
<th>Soft IoU (probe)</th>
<th>Mean-mask baseline</th>
<th>Probe / baseline</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single instance</td>
<td>448</td>
<td><strong>0.181</strong></td>
<td>0.062</td>
<td>2.9×</td>
</tr>
<tr class="even">
<td>Oblique single</td>
<td>160</td>
<td><strong>0.456</strong></td>
<td>0.300</td>
<td>1.5×</td>
</tr>
<tr class="odd">
<td>Multi N = 2</td>
<td>48</td>
<td><strong>0.278</strong></td>
<td>0.094</td>
<td>3.0×</td>
</tr>
<tr class="even">
<td>Multi N = 3</td>
<td>48</td>
<td><strong>0.268</strong></td>
<td>0.118</td>
<td>2.3×</td>
</tr>
<tr class="odd">
<td>Multi N = 5</td>
<td>48</td>
<td><strong>0.219</strong></td>
<td>0.123</td>
<td>1.8×</td>
</tr>
<tr class="even">
<td>Multi N = 8</td>
<td>48</td>
<td><strong>0.228</strong></td>
<td>0.127</td>
<td>1.8×</td>
</tr>
</tbody>
</table>
<div id="fig-polygon" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-polygon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_polygon_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-polygon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Polygon-from-CLS at 32×32, 4-band 8-hull rebuild. Across all strata the ridge probe lifts soft-IoU 2–3× above the position-blind mean-mask baseline. The earlier “collapse to baseline at N≥2” claim from the 2-hull synthetic-NIR build does <em>not</em> reproduce here — with 8 hulls and real NIR, the multi-N probe maintains a meaningful lift. Oblique singles are the strongest stratum because the elongated alpha mask has a strong principal axis the CLS can encode.
</figcaption>
</figure>
</div>
<p>What “lift above baseline” actually looks like: the chip on top, the ground-truth alpha mask in the middle, and the probe-predicted soft mask at the bottom. Median-IoU chip from each stratum (no cherry-picking) — single, oblique, multi N=3, multi N=8.</p>
<div id="fig-polygon-visual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-polygon-visual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_polygon_visual_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-polygon-visual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Polygon-from-CLS visual: chip → ground-truth mask → probe prediction, side by side for each stratum. Multi-output Ridge on 1024-D CLS, 5-fold CV. Soft mask shown in magma (0 → 1). At single and oblique, the prediction lights up the actual hull silhouette. At N=3 and N=8, the prediction lights up “where the boats are in general” — silhouette-grade across instances, not per-instance.
</figcaption>
</figure>
</div>
<p><strong>How the prediction is made.</strong> The probe is one <strong>multi-output Ridge regression</strong>: 1024-D CLS input → 1024-D output, where each output dimension is one cell of a 32×32 mask grid (32 × 32 = 1024 cells; this happens to match Clay’s patch-token grid because chip 256 / patch 8 = 32, but the probe doesn’t read patches — it reads the single CLS vector). One closed-form solve per fold, ~one second on a laptop, with α=1 regularisation to keep the 1M parameters under control given only ~900 training chips.</p>
<p><strong>How the ground truth is made.</strong> For every composite chip we built, we already know exactly where each hull was pasted — <code>(hull, scale, rotation, position)</code> for single instances, plus the deterministic seed for cardinality variants. So we can re-trace the alpha channel analytically: take the canonical hull’s alpha mask, apply the same resize / rotate / paste at the recorded position, repeat per instance, take the per-pixel max. That gives the 256×256 binary mask without re-rendering pixels. We then mean-pool 8×8 blocks down to 32×32 — soft per-cell occupancy in [0, 1].</p>
<p><strong>How the soft-IoU is scored.</strong> Per chip, intersection = <code>sum(min(pred, gt))</code> over the 1024 cells, union = <code>sum(max(pred, gt))</code>, and <code>IoU = intersection / union</code>. Soft because both pred and gt are continuous in [0, 1]. Reported in the bar chart and table above as the mean over 5-fold held-out chips per stratum.</p>
<p><strong>Reading.</strong> The CLS does carry a low-resolution silhouette signal across all strata, including multi-instance — corrected from the legacy 2-hull claim that it collapses to baseline at N≥2. What it <em>doesn’t</em> carry is <strong>per-instance addressing</strong>: a probe trained on a single chip-level target cannot pick out <em>which</em> of the N boats the question is about. That gap is what the per-instance addressing panel above shows.</p>
<div id="fig-tldr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tldr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_tldr_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tldr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: TL;DR Summary — linear-probe scores (LinearSVC for classification, Ridge for R²) trained on the embedding. Blue: within-object 5-fold (optimistic). Orange: LOBO held-out hull. Cosine-NN is shown elsewhere (per-hull strips, hull-similarity matrix); this figure is probe-only. Position is the only factor that flattens to chance at LOBO.
</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="dimensions-are-enough-for-some-properties" class="level2">
<h2 class="anchored" data-anchor-id="dimensions-are-enough-for-some-properties">64 Dimensions are enough for some properties</h2>
<p>We tested probe scores across different input sizes. We tested both direct increasing slices from the first dimensions (“native dims-0:K”), and increasing components of a PCA. Native dimensions require no extra computation. For rotation, scale, and count, the probe hits ~95% of its max performance by <strong>64 dimensions</strong>. Position is the only property that the <em>native</em> prefix can’t recover at 256 dims (0.73 vs 0.90 raw) — a PCA at 256 components recovers it (0.91), so the signal is there, just not concentrated in the first 256 raw dims.</p>
<p>This is a deployment-grade infrastructure win. <strong>Storing a 64-D native prefix is a 16× index compression</strong> that retains the geometric brain of the foundation model — for every property except chip-relative position, where you either keep the full 1024 or store a 256-D PCA basis alongside.</p>
<div id="fig-dims" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_dims_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Probe score vs input dimensionality — native dims-0:K tracks raw 1024 closely for rotation, scale, and count. Position is the only property where native-prefix-256 lags raw 1024; a PCA-256 recovers it.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Probe</th>
<th>dims-0:16</th>
<th>dims-0:64</th>
<th>dims-0:256</th>
<th>PCA-16</th>
<th>PCA-64</th>
<th>PCA-256</th>
<th>raw 1024</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rotation 4-cls</td>
<td>0.72</td>
<td>0.86</td>
<td>0.90</td>
<td>0.59</td>
<td>0.89</td>
<td>0.93</td>
<td><strong>0.94</strong></td>
</tr>
<tr class="even">
<td>Scale R²</td>
<td>0.94</td>
<td>0.99</td>
<td>0.997</td>
<td>0.97</td>
<td>0.997</td>
<td>0.998</td>
<td><strong>0.998</strong></td>
</tr>
<tr class="odd">
<td>Count R²</td>
<td>0.81</td>
<td>0.98</td>
<td>0.993</td>
<td>0.92</td>
<td>0.994</td>
<td>0.996</td>
<td><strong>0.996</strong></td>
</tr>
<tr class="even">
<td>Position 9-cls</td>
<td>0.21</td>
<td>0.53</td>
<td>0.73</td>
<td>0.14</td>
<td>0.73</td>
<td>0.91</td>
<td><strong>0.90</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="the-operational-playbook" class="level2">
<h2 class="anchored" data-anchor-id="the-operational-playbook">The Operational Playbook</h2>
<p>How do you deploy this at planet scale?</p>
<ol type="1">
<li><strong>Index Once.</strong> Precompute Clay v1.5 embeddings for your entire corpus, or use our <a href="https://lgnd.ai/lgnd-api">Lgnd API</a>.</li>
<li><strong>Train the Probe per Question.</strong> Label enough chips per question to create linear probes and test how well they generalize, and how many dimensions are needed. Then query your corpus. If you are interested in upcoming LGND tooling to facilitate this, <a href="https://lgnd.ai/contact">let us know</a>.</li>
</ol>
<p><strong>Three places linear probes change the agent’s job.</strong></p>
<ol type="1">
<li><strong>First-pass filter.</strong> <em>“Find chips with at least 3 boats”</em> becomes a single filter on the count column. The agent never sees the 99% of the corpus where N=0,1,2.</li>
<li><strong>Retrieval cue.</strong> <em>“Tanker pointed roughly towards port”</em> becomes the conjunction of three probe-column filters (<code>is_boat = 1</code>, <code>rotation e.g. 180° ± 45°</code>, <code>near_refinery_POI = 1</code>) plus a final agent verification step on the surviving few.</li>
<li><strong>Reranker (the binding case).</strong> Cosine retrieval cannot distinguish <em>boat-north / vehicle-south</em> from <em>vehicle-north / boat-south</em>. A linear probe on the same vector hits 0.87. For change-detection workflows specifically, this is the deployment story: pre/post comparisons of the same scene across time will produce embeddings that are nearly identical to cosine <em>even when the compositional content has changed</em>. A probe trained on “is this configuration A or configuration B?” is the rerank instrument that converts the cosine null into an actionable signal.</li>
</ol>
<p><strong>Where the probe runs out.</strong> Per-instance addressing — <em>“which of the N boats is the tanker?”</em>, pixel-precise polygons for damage assessment, attributing a property to a <em>specific</em> instance among multiple — is not in the CLS at all. Position is recoverable per-hull but does not transfer linearly to held-out hulls. Cross-scale and cross-vessel-class generalisation are partial. For those, a rough filter with the linear probes might help filter out clear cases, but the agent has to do the work — patch tokens with attention, SAM, Mask-RCNN, or full agentic reasoning over the chip pixels. The probe is the cheap layer that decides <em>whether</em> the agent has to, enabling much more efficient compute budget allocation.</p>
</section>
<section id="appendix-methods-caveats" class="level2">
<h2 class="anchored" data-anchor-id="appendix-methods-caveats">Appendix: Methods &amp; Caveats</h2>
<section id="lobo-spread" class="level3">
<h3 class="anchored" data-anchor-id="lobo-spread">LOBO spread</h3>
<p>We don’t report means without spreads. Our <strong>n=8 hand-digitized hulls</strong> let us see the failure modes. Rotation accuracy 0.76 is a mean; the per-hull strip plot below shows boat_07 tanks to 0.30. The spread is the signal: a deployment that depends on per-chip guarantees should add a confidence column and route low-confidence cases to a heavier instrument.</p>
<div id="fig-lobo-strip" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lobo-strip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_lobo_strip_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lobo-strip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: LOBO per-hull spread for all 5 probes. Each dot is one of the 8 held-out hulls; the dashed line is the LOBO mean. Rotation 4-cls and count R² have visible per-hull tails (boat_07 / boat_1+2+8). Scale R² is uniformly tight. Position is uniformly weak (~chance 0.111 for all hulls).
</figcaption>
</figure>
</div>
</section>
<section id="per-probe-hull-matrix-where-cosine-and-probe-disagree-per-hull" class="level3">
<h3 class="anchored" data-anchor-id="per-probe-hull-matrix-where-cosine-and-probe-disagree-per-hull">Per-(probe × hull) matrix — where cosine and probe disagree per hull</h3>
<p>The bar chart in §<a href="#tldr-the-findings-grouped-by-value">TL;DR</a> gives a probe-level mean. Per-hull, the means hide reversals — most importantly <strong>boat_07 rotation 4-cls</strong>, where cosine top-5 NN (0.52) actually <em>beats</em> the linear probe (0.30) because the trained probe overfits to the 7-hull pool while cosine retrieval doesn’t fit a hyperplane. That’s an argument for <strong>hull-distance-conditional routing</strong>: cosine-NN if the query embedding is far from the training pool, probe if it’s near.</p>
<div id="fig-cos-vs-probe-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cos-vs-probe-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_cos_vs_probe_matrix_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cos-vs-probe-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Per-(probe × held-out hull) matrix of LOBO scores. Left: cosine top-5 NN. Right: linear probe. Same 1024-D CLS, same split, two readouts. Rotation rows: probe matrix is uniformly greener (probe lifts every hull) <em>except</em> boat_07. Scale and count rows: cosine matrix matches or beats probe per hull. Position rows: both fail at LOBO.
</figcaption>
</figure>
</div>
</section>
<section id="how-distinct-are-the-8-hulls-really" class="level3">
<h3 class="anchored" data-anchor-id="how-distinct-are-the-8-hulls-really">How Distinct Are the 8 Hulls Really?</h3>
<p>We only tested here the case of ship hulls, and only 8 of them. We do not yet know how well these results will generalize to other classes of semantics (buildings, roads, agriculture, … ) or properties (damaged, flooded, … ). But we can at least check how distinct these 8 hulls are in embedding space. The mean off-diagonal cosine is 0.975 (range [0.956, 0.990]) — they’re geometrically distinct but live in a tight neighbourhood of the embedding manifold. Read every LOBO number below as “generalisation within this neighbourhood”, not “generalisation across semantics or even vessel families”.</p>
<div id="fig-hullsim" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hullsim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/fig_hullsim_4b.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hullsim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Cosine similarity matrix on the 8 canonical hull embeddings (centered on water, rotation 0°, scale 0.25). Off-diagonal mean 0.975 (range [0.956, 0.990]). The hulls are geometrically distinct but live in a tight neighbourhood of the embedding manifold — every LOBO number is generalisation <em>within this neighbourhood</em>, not across vessel families.
</figcaption>
</figure>
</div>
</section>
<section id="detailed-stats-table" class="level3">
<h3 class="anchored" data-anchor-id="detailed-stats-table">Detailed Stats Table</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Probe</th>
<th>Within-object (5-fold)</th>
<th>LOBO (8-hull mean)</th>
<th>Chance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rotation 4-cls (N/E/S/W)</td>
<td>0.94</td>
<td>0.76 [0.60, 0.90]</td>
<td>0.25</td>
</tr>
<tr class="even">
<td>Rotation 8-bin (cardinal+oblique)</td>
<td>0.93</td>
<td>0.80 [0.71, 0.88]</td>
<td>0.125</td>
</tr>
<tr class="odd">
<td>Rotation continuous (sin/cos Ridge)</td>
<td>17.8° MAE</td>
<td>39.5° MAE</td>
<td>90° MAE</td>
</tr>
<tr class="even">
<td>Scale R² (5 levels)</td>
<td>0.998</td>
<td>0.94 [0.89, 0.98]</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>Count R² (single hull)</td>
<td>0.996</td>
<td>0.84 [0.73, 0.96]</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>Count R² (mixed hulls)</td>
<td>0.92</td>
<td>— <em>(no LOBO design)</em></td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>Position 9-cls @ scale 0.25</td>
<td>0.89</td>
<td>0.24 [0.20, 0.29]</td>
<td>0.111</td>
</tr>
<tr class="even">
<td>Binding probe (“boat1 at top?”)</td>
<td>0.87 (perm-p&lt;0.005)</td>
<td>—</td>
<td>0.50</td>
</tr>
</tbody>
</table>
<p>LOBO numbers are mean ± 95% bootstrap CI across the 8 held-out hulls (2,000 resamples each). 5-fold numbers are mean across folds of 80/20 train/test splits (same hulls in train and test).</p>
</section>
<section id="reproduce" class="level3">
<h3 class="anchored" data-anchor-id="reproduce">Reproduce</h3>
<p>All the post’s compute lives in <strong>two files</strong>: <code>pipeline.py</code> (715 lines — compose → embed → probe → binding → polygon → ELLE → clipping → widget) and <code>figures.py</code> (478 lines — every figure in the post). Each is a thin CLI over a self-contained module. Code in the <a href="https://github.com/EarthLegend/devlogs">devlogs repo</a>.</p>
<p>The encoder is the public <a href="https://github.com/Clay-foundation/model">Clay foundation model</a> — NAIP is a native Clay collection, so the encoder + band metadata + datacube helpers all ship there. Outside the encoder, the pipeline is plain PyTorch + NumPy + scikit-learn (Ridge, LinearSVC, KFold) — nothing exotic.</p>
<p><strong>Get the Clay v1.5 encoder weights</strong> (~1.2 GB, extracted from the public 5 GB checkpoint):</p>
<pre><code># Download clay-v1.5.ckpt from https://huggingface.co/made-with-clay/Clay (file: v1.5/clay-v1.5.ckpt)
export CLAY_CKPT=/path/to/clay-v1.5.ckpt
export CLAY_ENCODER_PT="$PWD/clay-v1.5_encoder.pt"
python stream_extract_encoder.py     # streams the ZIP-checkpoint without loading 5 GB into RAM</code></pre>
<p>The ELLE step (<code>pipeline.py elle</code>) additionally needs a <code>clay_naip_pairs.pt</code> file with paired (CLS-embedding, reconstruction-loss) tensors for a few thousand NAIP chips — same artefact described in our companion <a href="../2026-03-01-self-aware-embeddings/">ELLE devlog</a>, which has the recipe to generate it. You can skip the ELLE step and still run every other command.</p>
<p><strong>Run.</strong></p>
<pre><code>python pipeline.py compose          # 1,042 4-band composite chips from canonicals
python pipeline.py embed 9999       # full Clay v1.5 embedding pass (resumable; embed [SECS] is a wall-clock budget, default 40 s for sandboxed reruns — pass a large value to finish in one shot)
python pipeline.py probes           # within + LOBO + rotcont + hullsim + bootstrap
python pipeline.py binding          # boat1↔boat2 swap test (re-embeds 96 chips internally)
python pipeline.py polygon          # polygon-from-CLS soft-IoU + specific-boat
python pipeline.py cosvsprobe       # cosine top-5 NN vs linear probe under LOBO
python pipeline.py dims             # dims-0:K vs PCA-K vs raw 1024
python pipeline.py elle             # ELLE manifold gauge + per-hull confidence (needs clay_naip_pairs.pt — see above)
python pipeline.py clipping         # alpha-overflow audit
python pipeline.py widget 9999      # boat_06 cross-product widget data (same SECS-budget pattern as embed)
python figures.py all               # render all 17 figures</code></pre>
<p><code>pipeline.py all</code> runs every step in order with default wall-clock budgets, which is convenient for resumable reruns but <strong>does not finish a fresh embed pass</strong> (the default <code>embed</code> budget is 40 s) — on first run, call <code>embed 9999</code> separately, then <code>all</code>.</p>
<p>The Clay v1.5 encoder forward pass is single-CPU friendly (no GPU required); <code>embed</code> is the long pole and runs in tens of minutes on a laptop. Every other step is seconds-to-a-minute. Both <code>embed</code> and <code>widget</code> write resumable state, so re-running picks up where it left off.</p>
<p>Three one-off setup helpers stay separate from the main pipeline: <code>stream_extract_encoder.py</code> (covered above), <code>polygons_wide_to_canonicals.py</code> (QGIS polygon → 4-band canonical extraction), and <code>fetch_wide_4band_tiff.py</code> (raw NAIP TIFF fetching from MPC). The latter two only matter if you want to rebuild the canonical hulls and water tile from scratch — the <code>assets/</code> directory in the repo already ships them.</p>
</section>
</section>
<section id="prior-art" class="level2">
<h2 class="anchored" data-anchor-id="prior-art">Prior Art</h2>
<p><em>Backbone, EO foundation-model siblings.</em></p>
<ul>
<li><strong>He et al.&nbsp;2022</strong> — <em><a href="https://arxiv.org/abs/2111.06377">Masked Autoencoders Are Scalable Vision Learners</a></em> (CVPR 2022). The backbone of Clay v1.5. Pixel reconstruction at absolute positions is the most parsimonious explanation for geometric axes surviving the single-CLS readout.</li>
<li><strong>Cong et al.&nbsp;2022</strong> — <em><a href="https://arxiv.org/abs/2207.08051">SatMAE: Pre-training Transformers for Temporal and Multi-Spectral Satellite Imagery</a></em> (NeurIPS 2022). Linear-probe transfer evaluation is the standard discipline in EO foundation-model benchmarks. This work extends that discipline from classification-task transfer into a controlled multi-factor probe sweep on a single scene.</li>
<li><strong>Brown et al.&nbsp;2025</strong> — <em><a href="https://arxiv.org/abs/2507.22291">AlphaEarth Foundations: An embedding field model for accurate and efficient global mapping from sparse label data</a></em> (DeepMind). A direct sibling on the pre-indexed-embeddings-at-planet-scale architectural pattern: AEF ships annual 64-D embeddings per 10 m pixel; LGND ships per-chip 1024-D Clay embeddings across NAIP, S2, Landsat. Same wedge — embed once at index time, query many times after — measured here at the chip level for a different sensor stack.</li>
</ul>
<p><em>Probing as methodology.</em></p>
<ul>
<li><strong>Alain &amp; Bengio 2016</strong> — <em><a href="https://arxiv.org/abs/1610.01644">Understanding intermediate layers using linear classifier probes</a>.</em> The foundational paper for probing-as-methodology. Every linear-probe number in this post stands on the discipline this paper established: train a fresh classifier on frozen features, read off what’s linearly recoverable.</li>
<li><strong>Hewitt &amp; Manning 2019</strong> — <em><a href="https://aclanthology.org/N19-1419/">A Structural Probe for Finding Syntax in Word Representations</a></em> (NAACL 2019). Showed entire syntax trees are linearly recoverable from BERT/ELMo geometry. Our finding is the EO analogue: geometric factors (rotation, count, size, content×position binding) are linearly recoverable from Clay’s CLS.</li>
<li><strong>Kim et al.&nbsp;2018</strong> — <em><a href="https://arxiv.org/abs/1711.11279">Quantitative Testing with Concept Activation Vectors (TCAV)</a></em> (ICML 2018). Our probes are TCAV applied to satellite imagery — concept activation vectors trained on a controlled stimulus set, validated by the held-out generalization (LOBO) we report here.</li>
</ul>
<p><em>CLS geometry, anisotropy, register artefacts.</em></p>
<ul>
<li><strong>Ethayarajh 2019</strong> — <em><a href="https://arxiv.org/abs/1909.00512">How Contextual are Contextualized Word Representations?</a></em> (EMNLP 2019). The underlying reason ViT CLS cosines saturate near 1.0 — and why our binding test recovers the signal via a probe but not via cosine.</li>
<li><strong>Darcet et al.&nbsp;2024</strong> — <em><a href="https://arxiv.org/abs/2309.16588">Vision Transformers Need Registers</a></em> (ICLR 2024). CLS-token artefacts matter for chip-level probes like ours; a register-equipped Clay variant would be a cleaner canvas for the position-fails-at-LOBO finding specifically.</li>
</ul>
<p><em>Compositional binding, counting, disentanglement.</em></p>
<ul>
<li><strong>Yuksekgonul et al.&nbsp;2023</strong> — <em><a href="https://arxiv.org/abs/2210.01936">When and Why Vision-Language Models Behave like Bags-of-Words</a></em> (ICLR 2023, oral). The canonical compositional-binding-failure result for VLMs: CLIP fails the ARO benchmark for attribute binding and word order. Our binding test is the EO foundation-model instantiation — same finding (cosine retrieval cannot deliver compositional binding), different stimulus class, controlled to two real hulls + a noise floor + a 200-permutation test.</li>
<li><strong>Paiss, Chefer, Wolf 2023</strong> — <em><a href="https://arxiv.org/abs/2302.12066">Teaching CLIP to Count to Ten</a></em> (ICCV 2023). CLIP needed explicit counting supervision. Clay’s R² ≈ 0.99 within-object (0.84 LOBO) with no language supervision is a (modest) data point for the MAE-reconstruction-teaches-counting side.</li>
<li><strong>Locatello et al.&nbsp;2019</strong> — <em><a href="https://arxiv.org/abs/1811.12359">Challenging Common Assumptions in the Unsupervised Learning of Disentangled Representations</a></em> (ICML 2019, best paper). Disentanglement-as-a-frame is contested: without inductive biases, well-disentangled models cannot be identified without supervision. We don’t claim factor disentanglement here — we claim factor <em>recoverability</em> via supervised linear probes, which is the weaker, identifiable claim.</li>
</ul>
<p><em>Dimensionality reduction critique.</em></p>
<ul>
<li><strong>Chari &amp; Pachter 2023</strong> — <em><a href="https://doi.org/10.1371/journal.pcbi.1011288">The Specious Art of Single-Cell Genomics</a></em> (PLOS Computational Biology). Their argument is that UMAP/t-SNE <em>fabricate</em> structure. Our finding is different — we show UMAP <em>loses</em> count and is indistinguishable from PCA-2 on the rest. Same concern, different symptom.</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/devlogs\.lgnd\.ai\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb3" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Cheaper than a pixel, faster than an agent; the geoembedding knows more than you think"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Clay embeddings do contain semantic information like location, size, orientation, and count of semantics within the image. Readable with linear probes."</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2026-04-22</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Bruno Sanchez-Andrade Nuno"</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [embeddings, foundation-models, clay, probing]</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "This post shows that Clay embeddings do contain semantic information like location, size, orientation, and count. And the mechanism to scale this retrieval to planetary scale, without agents or reading pixels."</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> "assets/boat1_native_4b.jpg"</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="an">page-layout:</span><span class="co"> full</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">  enabled: false</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="an">resources:</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - "assets/widget_data_4b.json"</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - "assets/water_native_4b.jpg"</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - "assets/canonical_boat_06_4b_preview.png"</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - "assets/SOURCE.txt"</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co">  - "assets/boats.geojson"</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="fu">## Agents, pixels or images</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>GeoAI is proving to be a powerful tool for understanding the Earth. There are three main pillars of this progress: agents to orchestrate complex reasoning, pull pixels, and iterate towards results; geo-embeddings for each pixel, where we convert patterns of raw radiance into universal indices of semantics; and geo-embeddings of patches of pixels like 256×256 "chips" all at once to create a single embedding for the whole scene. Agents are hard to scale globally since they scale with usage. Pixel embeddings are efficient semantic compressions but one-per-pixel scales poorly, especially when we want high spatial and temporal resolution. Chip embeddings are a middle ground — orders of magnitude less volume, and allowing grids of tiles — but they have typically been considered unable to efficiently translate that "semantic within" into *where* exactly or *what* properties.</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>The goal of this post is to take a simple case of boats on water and see if we can use chip embeddings to retrieve where they are in the image, their orientation, their size, and their count. Not only do we prove that the information is there, but we also show how to retrieve it with a simple linear probe — orders of magnitude cheaper than an agent.</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>We believe this is a critical piece to more efficiently orchestrate agents, pixel embeddings, and chip embeddings. To the degree we can extract semantic properties through these probes, they become the **think-fast** mode under any agentic flow: used as first-pass filters, retrieval cues, or rerankers that decide which candidates the expensive agent, pixel embeddings, or pixel CV should look at.</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cosine is Blind to Binding</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>In any standard vector database using **cosine similarity** on Clay v1.5 embeddings, these two chips — `boat1@TOP+boat2@BOT` and `boat1@BOT+boat2@TOP` — are **99.93% identical**. To a retrieval engine, they are the same scene. If you re-rendered Chip A with different water noise, it would actually look *more* different (cosine 0.9986) than the swap. **Standard vector search is blind to the bound arrangement of content.** Yet, a **1µs linear probe** — a single dot product on the same 1024-D vector — distinguishes the swap at **0.87 accuracy** (permutation p &lt; 0.005, i.e. fewer than 1 in 200 random label-shuffles match the trained probe's score). This proves that the embedding knows far more about the image it encodes.</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Thesis: Cheaper than a pixel, faster than an agent</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>Every time we ask a question — *"Is this tanker pointed North?"* or *"Are there more than three boats here?"* — an agentic approach pays a tax in tokens and seconds to re-process pixels; a pixel-embedding approach pays a tax in storage and retrieval time to read from a separate index; and a custom-CV approach pays the tax of pulling the pixels and running a model on the chip.</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>But for the billions of chips already indexed by LGND, we discovered that that "reasoning" has already happened. It's sitting inside the 1024-D CLS embedding one linear probe away from being read — a dot product, ~1µs on a CPU.</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## Try it Yourself: The 1µs Readout {#widget}</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>Pick a hull state. The readout below shows what each linear probe "reads" from Clay's CLS for that exact chip. Watch the *probe* readings as you change one slider — this is the embedding's internal geometry being decoded in real-time.</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;style&gt;</span></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 { background:#0e0e12; color:#f0f0f0; padding:18px 16px; border-radius:8px; font-family: ui-sans-serif,system-ui,sans-serif; margin:1.5em 0; max-width:760px; }</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .row { display:grid; grid-template-columns: 256px 1fr; gap:20px; align-items:flex-start; }</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a><span class="in">  @media (max-width: 600px) { #pw4 .row { grid-template-columns: 1fr; } }</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 img, #pw4 canvas { width:100%; max-width:256px; aspect-ratio:1/1; border:1px solid #2a2a32; image-rendering:pixelated; background:#000; display:block; }</span></span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .controls &gt; * { margin-bottom:10px; }</span></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .axisrow { display:grid; grid-template-columns: 70px 1fr 90px; gap:10px; align-items:center; }</span></span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .axislbl { color:#4aa0ff; font-weight:600; font-size:13px; }</span></span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .axislvl { color:#f0f0f0; font-size:13px; font-weight:600; text-align:right; }</span></span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .controls input[type=range] { width:100%; }</span></span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .reads { background:#15151c; border:1px solid #2a2a32; border-radius:6px; padding:8px 12px; font-size:12px; line-height:1.6; margin-top:6px; }</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .reading { display:grid; grid-template-columns: 80px 1fr 1fr; gap:8px; padding:4px 0; align-items:center; }</span></span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .reading + .reading { border-top:1px solid #2a2a32; }</span></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .reading .axis { color:#a0a0a8; font-size:11px; }</span></span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 code { background:#26262e; color:#dde; padding:1px 5px; border-radius:3px; font-size:11px; }</span></span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .ok { color:#00dc78; }</span></span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .miss { color:#ffcc33; }</span></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .none { color:#888; font-style:italic; }</span></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .stats { color:#a0a0a8; font-size:11px; margin-top:8px; line-height:1.55; }</span></span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .footnote { color:#a0a0a8; font-size:11px; margin-top:12px; }</span></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a><span class="in">  #pw4 .nomatch { color:#ffcc33; font-size:12px; margin-top:6px; }</span></span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;/style&gt;</span></span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;div id="pw4"&gt;</span></span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;div class="row"&gt;</span></span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;div&gt;</span></span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;canvas id="pw4Chip" width="256" height="256" aria-label="composite chip painted live in the browser"&gt;&lt;/canvas&gt;</span></span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;div class="nomatch" id="pw4NoMatch"&gt;&lt;/div&gt;</span></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;/div&gt;</span></span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;div class="controls"&gt;</span></span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;div class="axisrow"&gt;</span></span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislbl"&gt;Size&lt;/div&gt;</span></span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;input id="pw4Size" type="range" min="0" step="1" value="1" /&gt;</span></span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislvl" id="pw4SizeLvl"&gt;—&lt;/div&gt;</span></span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;/div&gt;</span></span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;div class="axisrow"&gt;</span></span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislbl"&gt;Count&lt;/div&gt;</span></span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;input id="pw4Count" type="range" min="0" step="1" value="1" /&gt;</span></span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislvl" id="pw4CountLvl"&gt;—&lt;/div&gt;</span></span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;/div&gt;</span></span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;div class="axisrow"&gt;</span></span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislbl"&gt;Position&lt;/div&gt;</span></span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;input id="pw4Pos" type="range" min="0" step="1" value="4" /&gt;</span></span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislvl" id="pw4PosLvl"&gt;—&lt;/div&gt;</span></span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;/div&gt;</span></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;div class="axisrow"&gt;</span></span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislbl"&gt;Rotation&lt;/div&gt;</span></span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;input id="pw4Rot" type="range" min="0" step="1" value="0" /&gt;</span></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a><span class="in">        &lt;div class="axislvl" id="pw4RotLvl"&gt;—&lt;/div&gt;</span></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;/div&gt;</span></span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;div class="reads" id="pw4Reads"&gt;…&lt;/div&gt;</span></span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a><span class="in">      &lt;div class="stats" id="pw4Stats"&gt;&lt;/div&gt;</span></span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;/div&gt;</span></span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/div&gt;</span></span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;div class="footnote"&gt;All chips are composites of real 4-band NAIP vessel cutouts onto water. Predictions shown are from linear probes on the 1024-D CLS vector.&lt;/div&gt;</span></span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;/div&gt;</span></span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;script&gt;</span></span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a><span class="in">(function () {</span></span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a><span class="in">  const root = document.getElementById('pw4');</span></span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a><span class="in">  if (!root) return;</span></span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a><span class="in">  const CHIP = 256;</span></span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a><span class="in">  const POS9 = {</span></span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a><span class="in">    top_left:    [0.20, 0.20], top:    [0.50, 0.20], top_right:    [0.80, 0.20],</span></span>
<span id="cb3-108"><a href="#cb3-108" aria-hidden="true" tabindex="-1"></a><span class="in">    left:        [0.20, 0.50], center: [0.50, 0.50], right:        [0.80, 0.50],</span></span>
<span id="cb3-109"><a href="#cb3-109" aria-hidden="true" tabindex="-1"></a><span class="in">    bottom_left: [0.20, 0.80], bottom: [0.50, 0.80], bottom_right: [0.80, 0.80],</span></span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a><span class="in">  };</span></span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a><span class="in">  const HULL = 'boat_06';</span></span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a><span class="in">  const HULL_FILE = 'canonical_boat_06_4b_preview.png';</span></span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a><span class="in">  const WATER_FILE = 'water_native_4b.jpg';</span></span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a><span class="in">  const fmtPos = v =&gt; v ? v.replace(/_/g, ' ') : '—';</span></span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a><span class="in">  const fmtHull = h =&gt; h ? h.replace(/^boat_?/, 'b') : '—';</span></span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a><span class="in">  function loadImg(src) {</span></span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a><span class="in">    return new Promise((resolve, reject) =&gt; {</span></span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a><span class="in">      const img = new Image();</span></span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a><span class="in">      img.onload = () =&gt; resolve(img);</span></span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a><span class="in">      img.onerror = () =&gt; reject(new Error('failed to load ' + src));</span></span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a><span class="in">      img.src = src;</span></span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a><span class="in">    });</span></span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a><span class="in">  }</span></span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a><span class="in">  Promise.all([</span></span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a><span class="in">    fetch('assets/widget_data_4b.json').then(r =&gt; r.json()),</span></span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a><span class="in">    loadImg('assets/' + WATER_FILE),</span></span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a><span class="in">    loadImg('assets/' + HULL_FILE),</span></span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a><span class="in">  ]).then(([d, water, hullImg]) =&gt; {</span></span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a><span class="in">    const chips = d.chips;</span></span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a><span class="in">    const canvas = root.querySelector('#pw4Chip');</span></span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a><span class="in">    const ctx = canvas.getContext('2d');</span></span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a><span class="in">    const sliders = {</span></span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a><span class="in">      size:     { el: root.querySelector('#pw4Size'),  lvl: root.querySelector('#pw4SizeLvl'),</span></span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a><span class="in">                  levels: d.axes.size.levels,     fmt: v =&gt; v.toFixed(2),       idx: 1 },</span></span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a><span class="in">      count:    { el: root.querySelector('#pw4Count'), lvl: root.querySelector('#pw4CountLvl'),</span></span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a><span class="in">                  levels: d.axes.count.levels,    fmt: v =&gt; 'N = ' + v,         idx: 1 },</span></span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a><span class="in">      position: { el: root.querySelector('#pw4Pos'),   lvl: root.querySelector('#pw4PosLvl'),</span></span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a><span class="in">                  levels: d.axes.position.levels, fmt: v =&gt; fmtPos(v),          idx: 4 },</span></span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a><span class="in">      rotation: { el: root.querySelector('#pw4Rot'),   lvl: root.querySelector('#pw4RotLvl'),</span></span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a><span class="in">                  levels: d.axes.rotation.levels, fmt: v =&gt; v + '°',            idx: 0 },</span></span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a><span class="in">    };</span></span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a><span class="in">    Object.values(sliders).forEach(s =&gt; {</span></span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a><span class="in">      s.el.max = s.levels.length - 1;</span></span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a><span class="in">      s.el.value = s.idx;</span></span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a><span class="in">      s.el.addEventListener('input', e =&gt; { s.idx = parseInt(e.target.value, 10); update(); });</span></span>
<span id="cb3-146"><a href="#cb3-146" aria-hidden="true" tabindex="-1"></a><span class="in">    });</span></span>
<span id="cb3-147"><a href="#cb3-147" aria-hidden="true" tabindex="-1"></a><span class="in">    function placements(count, cx, cy) {</span></span>
<span id="cb3-148"><a href="#cb3-148" aria-hidden="true" tabindex="-1"></a><span class="in">      if (count &lt;= 1) return [[cx, cy]];</span></span>
<span id="cb3-149"><a href="#cb3-149" aria-hidden="true" tabindex="-1"></a><span class="in">      const offsets = [[0, 0], [-55, -35], [55, -35], [-55, 35], [55, 35],</span></span>
<span id="cb3-150"><a href="#cb3-150" aria-hidden="true" tabindex="-1"></a><span class="in">                       [0, -65], [0, 65], [-75, 0], [75, 0]];</span></span>
<span id="cb3-151"><a href="#cb3-151" aria-hidden="true" tabindex="-1"></a><span class="in">      const out = [];</span></span>
<span id="cb3-152"><a href="#cb3-152" aria-hidden="true" tabindex="-1"></a><span class="in">      for (let i = 0; i &lt; count &amp;&amp; i &lt; offsets.length; i++) {</span></span>
<span id="cb3-153"><a href="#cb3-153" aria-hidden="true" tabindex="-1"></a><span class="in">        const [dx, dy] = offsets[i];</span></span>
<span id="cb3-154"><a href="#cb3-154" aria-hidden="true" tabindex="-1"></a><span class="in">        out.push([</span></span>
<span id="cb3-155"><a href="#cb3-155" aria-hidden="true" tabindex="-1"></a><span class="in">          Math.max(36, Math.min(CHIP - 36, cx + dx)),</span></span>
<span id="cb3-156"><a href="#cb3-156" aria-hidden="true" tabindex="-1"></a><span class="in">          Math.max(36, Math.min(CHIP - 36, cy + dy)),</span></span>
<span id="cb3-157"><a href="#cb3-157" aria-hidden="true" tabindex="-1"></a><span class="in">        ]);</span></span>
<span id="cb3-158"><a href="#cb3-158" aria-hidden="true" tabindex="-1"></a><span class="in">      }</span></span>
<span id="cb3-159"><a href="#cb3-159" aria-hidden="true" tabindex="-1"></a><span class="in">      return out;</span></span>
<span id="cb3-160"><a href="#cb3-160" aria-hidden="true" tabindex="-1"></a><span class="in">    }</span></span>
<span id="cb3-161"><a href="#cb3-161" aria-hidden="true" tabindex="-1"></a><span class="in">    function paint(size, count, position, rotation) {</span></span>
<span id="cb3-162"><a href="#cb3-162" aria-hidden="true" tabindex="-1"></a><span class="in">      ctx.drawImage(water, 0, 0, CHIP, CHIP, 0, 0, CHIP, CHIP);</span></span>
<span id="cb3-163"><a href="#cb3-163" aria-hidden="true" tabindex="-1"></a><span class="in">      if (count === 0) return;</span></span>
<span id="cb3-164"><a href="#cb3-164" aria-hidden="true" tabindex="-1"></a><span class="in">      const longest = Math.max(hullImg.width, hullImg.height);</span></span>
<span id="cb3-165"><a href="#cb3-165" aria-hidden="true" tabindex="-1"></a><span class="in">      const targetLong = Math.max(4, Math.round(size * CHIP));</span></span>
<span id="cb3-166"><a href="#cb3-166" aria-hidden="true" tabindex="-1"></a><span class="in">      const ratio = targetLong / longest;</span></span>
<span id="cb3-167"><a href="#cb3-167" aria-hidden="true" tabindex="-1"></a><span class="in">      const w = hullImg.width * ratio, h = hullImg.height * ratio;</span></span>
<span id="cb3-168"><a href="#cb3-168" aria-hidden="true" tabindex="-1"></a><span class="in">      const [fx, fy] = POS9[position] || [0.5, 0.5];</span></span>
<span id="cb3-169"><a href="#cb3-169" aria-hidden="true" tabindex="-1"></a><span class="in">      const cx = fx * CHIP, cy = fy * CHIP;</span></span>
<span id="cb3-170"><a href="#cb3-170" aria-hidden="true" tabindex="-1"></a><span class="in">      const rad = (rotation || 0) * Math.PI / 180;</span></span>
<span id="cb3-171"><a href="#cb3-171" aria-hidden="true" tabindex="-1"></a><span class="in">      for (const [px, py] of placements(count, cx, cy)) {</span></span>
<span id="cb3-172"><a href="#cb3-172" aria-hidden="true" tabindex="-1"></a><span class="in">        ctx.save();</span></span>
<span id="cb3-173"><a href="#cb3-173" aria-hidden="true" tabindex="-1"></a><span class="in">        ctx.translate(px, py);</span></span>
<span id="cb3-174"><a href="#cb3-174" aria-hidden="true" tabindex="-1"></a><span class="in">        ctx.rotate(rad);</span></span>
<span id="cb3-175"><a href="#cb3-175" aria-hidden="true" tabindex="-1"></a><span class="in">        ctx.drawImage(hullImg, -w / 2, -h / 2, w, h);</span></span>
<span id="cb3-176"><a href="#cb3-176" aria-hidden="true" tabindex="-1"></a><span class="in">        ctx.restore();</span></span>
<span id="cb3-177"><a href="#cb3-177" aria-hidden="true" tabindex="-1"></a><span class="in">      }</span></span>
<span id="cb3-178"><a href="#cb3-178" aria-hidden="true" tabindex="-1"></a><span class="in">    }</span></span>
<span id="cb3-179"><a href="#cb3-179" aria-hidden="true" tabindex="-1"></a><span class="in">    function findExactMatch(size, count, position, rotation) {</span></span>
<span id="cb3-180"><a href="#cb3-180" aria-hidden="true" tabindex="-1"></a><span class="in">      if (count === 0) {</span></span>
<span id="cb3-181"><a href="#cb3-181" aria-hidden="true" tabindex="-1"></a><span class="in">        return chips.find(c =&gt; c.is_null &amp;&amp; c.source_id === 'null_water')</span></span>
<span id="cb3-182"><a href="#cb3-182" aria-hidden="true" tabindex="-1"></a><span class="in">            || chips.find(c =&gt; c.is_null);</span></span>
<span id="cb3-183"><a href="#cb3-183" aria-hidden="true" tabindex="-1"></a><span class="in">      }</span></span>
<span id="cb3-184"><a href="#cb3-184" aria-hidden="true" tabindex="-1"></a><span class="in">      return chips.find(c =&gt; c.hull === HULL &amp;&amp; c.size === size</span></span>
<span id="cb3-185"><a href="#cb3-185" aria-hidden="true" tabindex="-1"></a><span class="in">                           &amp;&amp; c.count === count &amp;&amp; c.position === position</span></span>
<span id="cb3-186"><a href="#cb3-186" aria-hidden="true" tabindex="-1"></a><span class="in">                           &amp;&amp; c.rotation === rotation);</span></span>
<span id="cb3-187"><a href="#cb3-187" aria-hidden="true" tabindex="-1"></a><span class="in">    }</span></span>
<span id="cb3-188"><a href="#cb3-188" aria-hidden="true" tabindex="-1"></a><span class="in">    function ok(axis, gt, pred) {</span></span>
<span id="cb3-189"><a href="#cb3-189" aria-hidden="true" tabindex="-1"></a><span class="in">      if (gt === null || gt === undefined) return null;</span></span>
<span id="cb3-190"><a href="#cb3-190" aria-hidden="true" tabindex="-1"></a><span class="in">      if (pred === null || pred === undefined) return null;</span></span>
<span id="cb3-191"><a href="#cb3-191" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'size')     return Math.abs(gt - pred) &lt;= 0.15;</span></span>
<span id="cb3-192"><a href="#cb3-192" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'count')    return Math.abs(gt - pred) &lt;= 1.0;</span></span>
<span id="cb3-193"><a href="#cb3-193" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'rotation') {</span></span>
<span id="cb3-194"><a href="#cb3-194" aria-hidden="true" tabindex="-1"></a><span class="in">        const dr = ((gt - pred + 540) % 360) - 180;</span></span>
<span id="cb3-195"><a href="#cb3-195" aria-hidden="true" tabindex="-1"></a><span class="in">        return Math.abs(dr) &lt;= 45;</span></span>
<span id="cb3-196"><a href="#cb3-196" aria-hidden="true" tabindex="-1"></a><span class="in">      }</span></span>
<span id="cb3-197"><a href="#cb3-197" aria-hidden="true" tabindex="-1"></a><span class="in">      return String(gt) === String(pred);</span></span>
<span id="cb3-198"><a href="#cb3-198" aria-hidden="true" tabindex="-1"></a><span class="in">    }</span></span>
<span id="cb3-199"><a href="#cb3-199" aria-hidden="true" tabindex="-1"></a><span class="in">    function fmtVal(axis, v) {</span></span>
<span id="cb3-200"><a href="#cb3-200" aria-hidden="true" tabindex="-1"></a><span class="in">      if (v === null || v === undefined) return '—';</span></span>
<span id="cb3-201"><a href="#cb3-201" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'size')     return Number(v).toFixed(2);</span></span>
<span id="cb3-202"><a href="#cb3-202" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'count')    return Number(v).toFixed(1);</span></span>
<span id="cb3-203"><a href="#cb3-203" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'rotation') return Math.round(Number(v)) + '°';</span></span>
<span id="cb3-204"><a href="#cb3-204" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'position') return fmtPos(v);</span></span>
<span id="cb3-205"><a href="#cb3-205" aria-hidden="true" tabindex="-1"></a><span class="in">      if (axis === 'hull')     return fmtHull(v);</span></span>
<span id="cb3-206"><a href="#cb3-206" aria-hidden="true" tabindex="-1"></a><span class="in">      return String(v);</span></span>
<span id="cb3-207"><a href="#cb3-207" aria-hidden="true" tabindex="-1"></a><span class="in">    }</span></span>
<span id="cb3-208"><a href="#cb3-208" aria-hidden="true" tabindex="-1"></a><span class="in">    function update() {</span></span>
<span id="cb3-209"><a href="#cb3-209" aria-hidden="true" tabindex="-1"></a><span class="in">      const size = sliders.size.levels[sliders.size.idx];</span></span>
<span id="cb3-210"><a href="#cb3-210" aria-hidden="true" tabindex="-1"></a><span class="in">      const count = sliders.count.levels[sliders.count.idx];</span></span>
<span id="cb3-211"><a href="#cb3-211" aria-hidden="true" tabindex="-1"></a><span class="in">      const position = sliders.position.levels[sliders.position.idx];</span></span>
<span id="cb3-212"><a href="#cb3-212" aria-hidden="true" tabindex="-1"></a><span class="in">      const rotation = sliders.rotation.levels[sliders.rotation.idx];</span></span>
<span id="cb3-213"><a href="#cb3-213" aria-hidden="true" tabindex="-1"></a><span class="in">      Object.entries(sliders).forEach(([k, s]) =&gt; { s.lvl.textContent = s.fmt(s.levels[s.idx]); });</span></span>
<span id="cb3-214"><a href="#cb3-214" aria-hidden="true" tabindex="-1"></a><span class="in">      paint(size, count, position, rotation);</span></span>
<span id="cb3-215"><a href="#cb3-215" aria-hidden="true" tabindex="-1"></a><span class="in">      const chip = findExactMatch(size, count, position, rotation);</span></span>
<span id="cb3-216"><a href="#cb3-216" aria-hidden="true" tabindex="-1"></a><span class="in">      const order = ['size','count','position','rotation'];</span></span>
<span id="cb3-217"><a href="#cb3-217" aria-hidden="true" tabindex="-1"></a><span class="in">      if (chip) {</span></span>
<span id="cb3-218"><a href="#cb3-218" aria-hidden="true" tabindex="-1"></a><span class="in">        root.querySelector('#pw4NoMatch').textContent = '';</span></span>
<span id="cb3-219"><a href="#cb3-219" aria-hidden="true" tabindex="-1"></a><span class="in">        const rows = order.map(name =&gt; {</span></span>
<span id="cb3-220"><a href="#cb3-220" aria-hidden="true" tabindex="-1"></a><span class="in">          const gt = chip.gt[name];</span></span>
<span id="cb3-221"><a href="#cb3-221" aria-hidden="true" tabindex="-1"></a><span class="in">          const pred = chip.pred[name];</span></span>
<span id="cb3-222"><a href="#cb3-222" aria-hidden="true" tabindex="-1"></a><span class="in">          const hit = ok(name, gt, pred);</span></span>
<span id="cb3-223"><a href="#cb3-223" aria-hidden="true" tabindex="-1"></a><span class="in">          const cls = hit === null ? 'none' : (hit ? 'ok' : 'miss');</span></span>
<span id="cb3-224"><a href="#cb3-224" aria-hidden="true" tabindex="-1"></a><span class="in">          const mark = hit === null ? '' : (hit ? '✓' : '✗');</span></span>
<span id="cb3-225"><a href="#cb3-225" aria-hidden="true" tabindex="-1"></a><span class="in">          const Cap = name.charAt(0).toUpperCase() + name.slice(1);</span></span>
<span id="cb3-226"><a href="#cb3-226" aria-hidden="true" tabindex="-1"></a><span class="in">          return '&lt;div class="reading"&gt;' +</span></span>
<span id="cb3-227"><a href="#cb3-227" aria-hidden="true" tabindex="-1"></a><span class="in">                   '&lt;div class="axis"&gt;' + Cap + '&lt;/div&gt;' +</span></span>
<span id="cb3-228"><a href="#cb3-228" aria-hidden="true" tabindex="-1"></a><span class="in">                   '&lt;div&gt;truth &lt;code&gt;' + fmtVal(name, gt) + '&lt;/code&gt;&lt;/div&gt;' +</span></span>
<span id="cb3-229"><a href="#cb3-229" aria-hidden="true" tabindex="-1"></a><span class="in">                   '&lt;div&gt;probe &lt;code class="' + cls + '"&gt;' + fmtVal(name, pred) + '&lt;/code&gt; ' + mark + '&lt;/div&gt;' +</span></span>
<span id="cb3-230"><a href="#cb3-230" aria-hidden="true" tabindex="-1"></a><span class="in">                 '&lt;/div&gt;';</span></span>
<span id="cb3-231"><a href="#cb3-231" aria-hidden="true" tabindex="-1"></a><span class="in">        });</span></span>
<span id="cb3-232"><a href="#cb3-232" aria-hidden="true" tabindex="-1"></a><span class="in">        root.querySelector('#pw4Reads').innerHTML = rows.join('');</span></span>
<span id="cb3-233"><a href="#cb3-233" aria-hidden="true" tabindex="-1"></a><span class="in">      } else {</span></span>
<span id="cb3-234"><a href="#cb3-234" aria-hidden="true" tabindex="-1"></a><span class="in">        root.querySelector('#pw4NoMatch').textContent = 'No measured embedding for this exact slider state — chip is painted on the fly. Move sliders to a measured combo to see probe predictions.';</span></span>
<span id="cb3-235"><a href="#cb3-235" aria-hidden="true" tabindex="-1"></a><span class="in">        const rows = order.map(name =&gt; {</span></span>
<span id="cb3-236"><a href="#cb3-236" aria-hidden="true" tabindex="-1"></a><span class="in">          const Cap = name.charAt(0).toUpperCase() + name.slice(1);</span></span>
<span id="cb3-237"><a href="#cb3-237" aria-hidden="true" tabindex="-1"></a><span class="in">          return '&lt;div class="reading"&gt;' +</span></span>
<span id="cb3-238"><a href="#cb3-238" aria-hidden="true" tabindex="-1"></a><span class="in">                   '&lt;div class="axis"&gt;' + Cap + '&lt;/div&gt;' +</span></span>
<span id="cb3-239"><a href="#cb3-239" aria-hidden="true" tabindex="-1"></a><span class="in">                   '&lt;div&gt;truth &lt;code&gt;—&lt;/code&gt;&lt;/div&gt;' +</span></span>
<span id="cb3-240"><a href="#cb3-240" aria-hidden="true" tabindex="-1"></a><span class="in">                   '&lt;div&gt;probe &lt;code class="none"&gt;—&lt;/code&gt;&lt;/div&gt;' +</span></span>
<span id="cb3-241"><a href="#cb3-241" aria-hidden="true" tabindex="-1"></a><span class="in">                 '&lt;/div&gt;';</span></span>
<span id="cb3-242"><a href="#cb3-242" aria-hidden="true" tabindex="-1"></a><span class="in">        });</span></span>
<span id="cb3-243"><a href="#cb3-243" aria-hidden="true" tabindex="-1"></a><span class="in">        root.querySelector('#pw4Reads').innerHTML = rows.join('');</span></span>
<span id="cb3-244"><a href="#cb3-244" aria-hidden="true" tabindex="-1"></a><span class="in">      }</span></span>
<span id="cb3-245"><a href="#cb3-245" aria-hidden="true" tabindex="-1"></a><span class="in">      const headline = order.map(k =&gt; `${k} &lt;code&gt;${d.axes[k].within_object_5fold}&lt;/code&gt;`).join(', ');</span></span>
<span id="cb3-246"><a href="#cb3-246" aria-hidden="true" tabindex="-1"></a><span class="in">      const lobo = order.map(k =&gt; `${k} &lt;code&gt;${d.axes[k].cross_hull_lobo}&lt;/code&gt;`).join(', ');</span></span>
<span id="cb3-247"><a href="#cb3-247" aria-hidden="true" tabindex="-1"></a><span class="in">      root.querySelector('#pw4Stats').innerHTML =</span></span>
<span id="cb3-248"><a href="#cb3-248" aria-hidden="true" tabindex="-1"></a><span class="in">        'Within-object 5-fold: ' + headline + '. Cross-hull LOBO: ' + lobo + '.';</span></span>
<span id="cb3-249"><a href="#cb3-249" aria-hidden="true" tabindex="-1"></a><span class="in">    }</span></span>
<span id="cb3-250"><a href="#cb3-250" aria-hidden="true" tabindex="-1"></a><span class="in">    update();</span></span>
<span id="cb3-251"><a href="#cb3-251" aria-hidden="true" tabindex="-1"></a><span class="in">  }).catch(e =&gt; {</span></span>
<span id="cb3-252"><a href="#cb3-252" aria-hidden="true" tabindex="-1"></a><span class="in">    root.innerHTML = 'Widget assets failed to load.';</span></span>
<span id="cb3-253"><a href="#cb3-253" aria-hidden="true" tabindex="-1"></a><span class="in">  });</span></span>
<span id="cb3-254"><a href="#cb3-254" aria-hidden="true" tabindex="-1"></a><span class="in">})();</span></span>
<span id="cb3-255"><a href="#cb3-255" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;/script&gt;</span></span>
<span id="cb3-256"><a href="#cb3-256" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-257"><a href="#cb3-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-258"><a href="#cb3-258" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Case: From Pixels to Primitives</span></span>
<span id="cb3-259"><a href="#cb3-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-260"><a href="#cb3-260" aria-hidden="true" tabindex="-1"></a>To prove what the embedding knows, we built a controlled path from raw imagery to extracted signals.</span>
<span id="cb3-261"><a href="#cb3-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-262"><a href="#cb3-262" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Raw Image:** We started with wide 4-band NAIP tiles of an SF Bay coastal anchorage.</span>
<span id="cb3-263"><a href="#cb3-263" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Canonical Extraction:** Using NIR+LAB signals, we hand-digitized 8 real vessel hulls in QGIS, straightened them to a horizontal principal axis, and saved them as 5-channel alpha cutouts (RGBN+A). We also extracted empty water as a semantically "flat" background.</span>
<span id="cb3-264"><a href="#cb3-264" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Factorial Synthetic Samples:** We wanted to study combinations of ship rotation, location in the chip, size, and number of ships (same or different hull mix), including null sets with no boats or white noise as background. The full combinatorial space exceeds **17,000 unique chips** (8 hulls × 5 sizes × 6 counts × 9 positions × 8 rotations), so we sampled an exploratory random grid of **1,042 chips**.</span>
<span id="cb3-265"><a href="#cb3-265" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>**Embedding and Probing:** Every chip was then embedded with the production Clay v1.5 encoder. We trained linear probes (Ridge or LinearSVC) to test if we could "read" these factors back off the frozen vector.</span>
<span id="cb3-266"><a href="#cb3-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-267"><a href="#cb3-267" aria-hidden="true" tabindex="-1"></a><span class="al">![Figure 1 — The Setup. Top: 8 hand-digitized hulls (RGB). Bottom: The same hulls in native NIR. Clay sees both. These are the "words" in the Dictionary of the Earth.](assets/fig_canonicals_4b.png)</span>{#fig-1}</span>
<span id="cb3-268"><a href="#cb3-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-269"><a href="#cb3-269" aria-hidden="true" tabindex="-1"></a><span class="al">![Figure 2 — The Samples. 32 random samples (seed=7) drawn from the 1,042-chip dataset. Every probe in this post trains and tests on draws from this distribution — different hulls, scales, rotations, positions, cardinalities, plus null variants.](assets/fig_perturb_4b.png)</span>{#fig-2}</span>
<span id="cb3-270"><a href="#cb3-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-271"><a href="#cb3-271" aria-hidden="true" tabindex="-1"></a>**Envelope of validity.** All 8 hulls come from the same coastal anchorage, similar size class (~10–25 m), composited onto a real 4-band water tile from the same source. The 8 canonical hulls sit at off-diagonal cosine **0.97** in embedding space — they're geometrically distinct but live in a *tight* neighbourhood of the manifold. Read every LOBO number below as "generalisation within this neighbourhood", not "generalisation across vessel families". Cross-anchorage, cross-vessel-class, cross-sensor, and leave-one-water-out replications are open follow-ups, not claims of this post.</span>
<span id="cb3-272"><a href="#cb3-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-273"><a href="#cb3-273" aria-hidden="true" tabindex="-1"></a>**A note on what these probes actually test.** Every probe in this post is a categorical or scalar linear readout on specific labels. The 4-class rotation probe is *literally* a "which-of-N/E/S/W?" classifier; the 8-bin extends to obliques; the continuous-rotation regression generalises further. The position probe is a "which-of-9-grid-cells?" classifier on chip-relative paste position. A high score means *this categorical or scalar distinction is linearly decodable from the CLS token across hulls* — not "Clay represents X in general". Where probes fail, they're failing this narrow test; the embedding may still encode the property non-linearly or in patch tokens.</span>
<span id="cb3-274"><a href="#cb3-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-275"><a href="#cb3-275" aria-hidden="true" tabindex="-1"></a>**Are the composites on-manifold?** A reasonable concern with paste-on-water composites is that they might sit in an out-of-distribution corner of the embedding manifold — a probe could then be reading "this is a composite" rather than the geometric factor we're labelling. Our companion devlog on **[ELLE — self-aware embeddings](../2026-03-01-self-aware-embeddings/)** trained a small head that predicts Clay's reconstruction loss directly from the CLS. Re-applied to this 4-band 8-hull build, ELLE confirms that composite chips of this kind sit *0.8–1.0σ below* the typical-NAIP difficulty distribution — inside Clay's natural manifold, slightly *easier* than the average NAIP chip Clay was trained on. Gaussian-noise nulls land at +0.73σ — distinctly off-manifold. ELLE separates the two cleanly.</span>
<span id="cb3-276"><a href="#cb3-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-277"><a href="#cb3-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-278"><a href="#cb3-278" aria-hidden="true" tabindex="-1"></a><span class="fu">## TL;DR The Findings: Grouped by Value</span></span>
<span id="cb3-279"><a href="#cb3-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-280"><a href="#cb3-280" aria-hidden="true" tabindex="-1"></a>We measured six primitives. We tested both **5-fold within-object** (leaving 20% of chips out for validation each fold; the same hulls appear in train and test — optimistic upper bound) and **LOBO (Leave-One-Boat-Out)** — train on 7 hulls, test on the 8th, repeated for each. n=8 hulls is not a big sample, but the goal is to check if the signal is there at all and to surface per-hull failure modes via the spread.</span>
<span id="cb3-281"><a href="#cb3-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-282"><a href="#cb3-282" aria-hidden="true" tabindex="-1"></a>Since our goal is maximum retrieval efficiency, we restrict ourselves to the cheapest approach: cosine similarity (which would enable the easiest retrieval), and linear probes under LOBO. No MLPs, no fine-tuning, no agents.</span>
<span id="cb3-283"><a href="#cb3-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-284"><a href="#cb3-284" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cosine-accessible properties</span></span>
<span id="cb3-285"><a href="#cb3-285" aria-hidden="true" tabindex="-1"></a>**Scale (R² 0.94 LOBO)** and **Count (R² 0.84 LOBO)** are the strongest and easiest signals to retrieve — both cosine similarity in-class and LOBO.</span>
<span id="cb3-286"><a href="#cb3-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-287"><a href="#cb3-287" aria-hidden="true" tabindex="-1"></a><span class="al">![Cosine-accessible — Scale and Count under LOBO. Each panel shows the per-hull spread (8 dots) plus the mean for cosine top-5 NN (blue) and the linear probe (orange). Both readouts work; cosine is slightly tighter on these two scalar properties because the target value tracks the dominant cosine axis. Dashed line is the within-object 5-fold ceiling.](assets/fig_pair_cosine_4b.png)</span>{#fig-pair-cosine}</span>
<span id="cb3-288"><a href="#cb3-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-289"><a href="#cb3-289" aria-hidden="true" tabindex="-1"></a>The reason cosine works here is mechanically simple: same-scale chips cluster together in cosine space, so top-K nearest-neighbour voting recovers the value. The figure below makes that concrete — at scale 0.25 the top-5 cosine neighbours are near-duplicates (cos ≥ 0.999); at scale 1.0 the top-5 stay at scale 1.0 (smaller variants of the same hull are absent). Cosine is *scale-biased* — it returns "is this the same scene?" not "is this the same hull at a different size?" — and for the scale-detection question, that bias is a feature, not a bug.</span>
<span id="cb3-290"><a href="#cb3-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-291"><a href="#cb3-291" aria-hidden="true" tabindex="-1"></a><span class="al">![Top-5 cosine neighbours of canonical hulls at two scales. **Top two rows:** boat1 and boat_05 at scale 0.25 — neighbours are near-duplicates (cos ≥ 0.999). **Bottom two rows:** the same hulls at scale 1.0 — neighbours stay at scale 1.0; smaller variants of the same hull are absent. Cosine retrieval clusters by scale; the linear probe supplies what cosine drops only for properties orthogonal to that clustering.](assets/fig_retrieval_4b.png)</span>{#fig-retrieval}</span>
<span id="cb3-292"><a href="#cb3-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-293"><a href="#cb3-293" aria-hidden="true" tabindex="-1"></a><span class="fu">### Probe-accesible properties</span></span>
<span id="cb3-294"><a href="#cb3-294" aria-hidden="true" tabindex="-1"></a>**Rotation (0.76 acc LOBO)** and **Binding (0.87 acc)** are where cosine retrieval collapses.</span>
<span id="cb3-295"><a href="#cb3-295" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Rotation:** A probe can sort N from S reliably across hulls (39° angular MAE); cosine retrieval is 26% less accurate here.</span>
<span id="cb3-296"><a href="#cb3-296" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Binding (i.e. content × position):** As shown in the "Boat Swap" case, standard vector search sits at chance (0.50), while a probe hits 0.87.</span>
<span id="cb3-297"><a href="#cb3-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-298"><a href="#cb3-298" aria-hidden="true" tabindex="-1"></a><span class="al">![Probe-accessible — Rotation and Binding under LOBO. **Rotation 4-cls (left):** cosine top-5 NN sits at 0.50 across all 8 hulls; the linear probe lifts it to 0.76 (one outlier — boat_07 at 0.30). **Binding (right):** cos(SWAP)=0.9993 ≈ cos(noise)=0.9986 — cosine cannot tell `boat1@TOP+boat2@BOT` apart from the same scene re-noised, so on the binding *task* it sits at chance (0.50). The probe hits 0.87 (perm shuffle mean 0.52, perm-p &lt; 0.005). The discriminating direction is in the embedding, just orthogonal to the dominant cosine axis.](assets/fig_pair_probe_4b.png)</span>{#fig-pair-probe}</span>
<span id="cb3-299"><a href="#cb3-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-300"><a href="#cb3-300" aria-hidden="true" tabindex="-1"></a>**Rotation, three nested probes.** The 4-class compass classifier is the easiest version (chance 0.25); the 8-bin extends to obliques (chance 0.125); the continuous-rotation regression generalises to any angle. The three give a coarse-to-fine view of how the embedding represents heading.</span>
<span id="cb3-301"><a href="#cb3-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-302"><a href="#cb3-302" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**4-cls** (n=448): within-object 0.94, LOBO 0.76 <span class="co">[</span><span class="ot">0.60, 0.90</span><span class="co">]</span>. boat_07 drops to 0.30.</span>
<span id="cb3-303"><a href="#cb3-303" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**8-bin** (n=608): within-object 0.93, LOBO 0.80 <span class="co">[</span><span class="ot">0.71, 0.88</span><span class="co">]</span>.</span>
<span id="cb3-304"><a href="#cb3-304" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Continuous** (sin/cos Ridge, n=608): within-object **17.8° MAE / 6.9° median**, LOBO **39.5° MAE** with worst hull (boat_08) at 66.8°.</span>
<span id="cb3-305"><a href="#cb3-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-306"><a href="#cb3-306" aria-hidden="true" tabindex="-1"></a>The continuous LOBO MAE is the most operationally honest number. It says: the embedding gives you a heading prior accurate to ~one octant on hulls it has never seen — coarse, not fine. The 4-class and 8-bin accuracies are higher because they bucket the angle, hiding the fine-grained miss.</span>
<span id="cb3-307"><a href="#cb3-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-308"><a href="#cb3-308" aria-hidden="true" tabindex="-1"></a><span class="al">![Continuous rotation regression. Left: angular MAE within-object vs LOBO. Right: per-hull LOBO MAE. boat_07 and boat_08 sit far above the mean — the rotation primitive is coarse, not smooth, on held-out hulls.](assets/fig_rotcont_4b.png)</span>{#fig-rotcont}</span>
<span id="cb3-309"><a href="#cb3-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-310"><a href="#cb3-310" aria-hidden="true" tabindex="-1"></a><span class="fu">### Agent-only properties</span></span>
<span id="cb3-311"><a href="#cb3-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-312"><a href="#cb3-312" aria-hidden="true" tabindex="-1"></a>**Position (0.24 acc LOBO)** and **Per-instance Addressing** fail at the CLS level.</span>
<span id="cb3-313"><a href="#cb3-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-314"><a href="#cb3-314" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>The embedding "knows" where a hull is if it has seen it before (0.89 within-object), but it doesn't generalize that knowledge linearly to new hulls.</span>
<span id="cb3-315"><a href="#cb3-315" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>For sub-chip localization or pixel-precise damage assessment, the agent *has* to look at the patches or the pixels. This is the SPEC for when to call the slow-thinker.</span>
<span id="cb3-316"><a href="#cb3-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-317"><a href="#cb3-317" aria-hidden="true" tabindex="-1"></a>**Three reference lines used in the figure below.** Most polygon-retrieval figures benchmark the probe against three references; we'll define them once here:</span>
<span id="cb3-318"><a href="#cb3-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-319"><a href="#cb3-319" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Mean-mask baseline.** For each fold, predict the *training-set mean alpha mask* for every test chip — same prediction for everyone. This is the position-blind null any chip-level probe must beat to demonstrate it carries actual chip-specific spatial signal.</span>
<span id="cb3-320"><a href="#cb3-320" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Soft IoU.** Per chip, <span class="in">`intersection / union`</span> where <span class="in">`intersection = sum(min(pred, gt))`</span> and <span class="in">`union = sum(max(pred, gt))`</span> over the 1024 cells of the 32×32 mask grid — both pred and gt continuous in <span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>. Soft IoU is bounded in <span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span> and reduces to standard IoU when both are binary.</span>
<span id="cb3-321"><a href="#cb3-321" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Union-oracle ceiling.** For a "find leftmost boat among N" task, the union of *all* N boats' masks is the upper bound for any readout that knows *where boats are* but cannot tell *which one is leftmost*. Scored against the leftmost-only target, this oracle caps at **1/N** (since at most 1 of N union-cells corresponds to the correct instance). Reaching the oracle means the readout is doing as well as a hull-aware-but-instance-blind detector could; staying below it means the readout is also missing the "where boats are" signal.</span>
<span id="cb3-322"><a href="#cb3-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-323"><a href="#cb3-323" aria-hidden="true" tabindex="-1"></a><span class="al">![Agent-only — Position and Per-instance Addressing both fail. **Position 9-cls (left):** cosine 0.27 and probe 0.24 sit essentially at the 1/9 chance line; the within-object 0.89 ceiling (dashed) does not transfer across hulls. **Per-instance addressing (right):** the ridge probe lifts above the mean-mask baseline at every N, but **caps at the union-oracle ceiling** (1/N) — a CLS-level readout cannot pick out *which* of N boats the question is about. At N=2 the probe captures 26% IoU vs the leftmost target when an instance-aware readout could reach 50%. The CLS doesn't expose addressable instance slots.](assets/fig_pair_agent_4b.png)</span>{#fig-pair-agent}</span>
<span id="cb3-324"><a href="#cb3-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-325"><a href="#cb3-325" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Polygon retrieval — silhouette is *partly* there, but instance-blind</span></span>
<span id="cb3-326"><a href="#cb3-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-327"><a href="#cb3-327" aria-hidden="true" tabindex="-1"></a>We also asked the harder question: can the CLS predict the chip's **per-cell mask** at 32×32 (matching Clay's patch grid)? A multi-output Ridge per fold; soft-IoU vs the ground-truth alpha mask.</span>
<span id="cb3-328"><a href="#cb3-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-329"><a href="#cb3-329" aria-hidden="true" tabindex="-1"></a>| Stratum | n | Soft IoU (probe) | Mean-mask baseline | Probe / baseline |</span>
<span id="cb3-330"><a href="#cb3-330" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|</span>
<span id="cb3-331"><a href="#cb3-331" aria-hidden="true" tabindex="-1"></a>| Single instance | 448 | **0.181** | 0.062 | 2.9× |</span>
<span id="cb3-332"><a href="#cb3-332" aria-hidden="true" tabindex="-1"></a>| Oblique single | 160 | **0.456** | 0.300 | 1.5× |</span>
<span id="cb3-333"><a href="#cb3-333" aria-hidden="true" tabindex="-1"></a>| Multi N = 2 | 48 | **0.278** | 0.094 | 3.0× |</span>
<span id="cb3-334"><a href="#cb3-334" aria-hidden="true" tabindex="-1"></a>| Multi N = 3 | 48 | **0.268** | 0.118 | 2.3× |</span>
<span id="cb3-335"><a href="#cb3-335" aria-hidden="true" tabindex="-1"></a>| Multi N = 5 | 48 | **0.219** | 0.123 | 1.8× |</span>
<span id="cb3-336"><a href="#cb3-336" aria-hidden="true" tabindex="-1"></a>| Multi N = 8 | 48 | **0.228** | 0.127 | 1.8× |</span>
<span id="cb3-337"><a href="#cb3-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-338"><a href="#cb3-338" aria-hidden="true" tabindex="-1"></a><span class="al">![Polygon-from-CLS at 32×32, 4-band 8-hull rebuild. Across all strata the ridge probe lifts soft-IoU 2–3× above the position-blind mean-mask baseline. The earlier "collapse to baseline at N≥2" claim from the 2-hull synthetic-NIR build does *not* reproduce here — with 8 hulls and real NIR, the multi-N probe maintains a meaningful lift. Oblique singles are the strongest stratum because the elongated alpha mask has a strong principal axis the CLS can encode.](assets/fig_polygon_4b.png)</span>{#fig-polygon}</span>
<span id="cb3-339"><a href="#cb3-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-340"><a href="#cb3-340" aria-hidden="true" tabindex="-1"></a>What "lift above baseline" actually looks like: the chip on top, the ground-truth alpha mask in the middle, and the probe-predicted soft mask at the bottom. Median-IoU chip from each stratum (no cherry-picking) — single, oblique, multi N=3, multi N=8.</span>
<span id="cb3-341"><a href="#cb3-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-342"><a href="#cb3-342" aria-hidden="true" tabindex="-1"></a><span class="al">![Polygon-from-CLS visual: chip → ground-truth mask → probe prediction, side by side for each stratum. Multi-output Ridge on 1024-D CLS, 5-fold CV. Soft mask shown in magma (0 → 1). At single and oblique, the prediction lights up the actual hull silhouette. At N=3 and N=8, the prediction lights up "where the boats are in general" — silhouette-grade across instances, not per-instance.](assets/fig_polygon_visual_4b.png)</span>{#fig-polygon-visual}</span>
<span id="cb3-343"><a href="#cb3-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-344"><a href="#cb3-344" aria-hidden="true" tabindex="-1"></a>**How the prediction is made.** The probe is one **multi-output Ridge regression**: 1024-D CLS input → 1024-D output, where each output dimension is one cell of a 32×32 mask grid (32 × 32 = 1024 cells; this happens to match Clay's patch-token grid because chip 256 / patch 8 = 32, but the probe doesn't read patches — it reads the single CLS vector). One closed-form solve per fold, ~one second on a laptop, with α=1 regularisation to keep the 1M parameters under control given only ~900 training chips.</span>
<span id="cb3-345"><a href="#cb3-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-346"><a href="#cb3-346" aria-hidden="true" tabindex="-1"></a>**How the ground truth is made.** For every composite chip we built, we already know exactly where each hull was pasted — <span class="in">`(hull, scale, rotation, position)`</span> for single instances, plus the deterministic seed for cardinality variants. So we can re-trace the alpha channel analytically: take the canonical hull's alpha mask, apply the same resize / rotate / paste at the recorded position, repeat per instance, take the per-pixel max. That gives the 256×256 binary mask without re-rendering pixels. We then mean-pool 8×8 blocks down to 32×32 — soft per-cell occupancy in <span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>.</span>
<span id="cb3-347"><a href="#cb3-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-348"><a href="#cb3-348" aria-hidden="true" tabindex="-1"></a>**How the soft-IoU is scored.** Per chip, intersection = <span class="in">`sum(min(pred, gt))`</span> over the 1024 cells, union = <span class="in">`sum(max(pred, gt))`</span>, and <span class="in">`IoU = intersection / union`</span>. Soft because both pred and gt are continuous in <span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>. Reported in the bar chart and table above as the mean over 5-fold held-out chips per stratum.</span>
<span id="cb3-349"><a href="#cb3-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-350"><a href="#cb3-350" aria-hidden="true" tabindex="-1"></a>**Reading.** The CLS does carry a low-resolution silhouette signal across all strata, including multi-instance — corrected from the legacy 2-hull claim that it collapses to baseline at N≥2. What it *doesn't* carry is **per-instance addressing**: a probe trained on a single chip-level target cannot pick out *which* of the N boats the question is about. That gap is what the per-instance addressing panel above shows.</span>
<span id="cb3-351"><a href="#cb3-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-352"><a href="#cb3-352" aria-hidden="true" tabindex="-1"></a><span class="al">![TL;DR Summary — linear-probe scores (LinearSVC for classification, Ridge for R²) trained on the embedding. Blue: within-object 5-fold (optimistic). Orange: LOBO held-out hull. Cosine-NN is shown elsewhere (per-hull strips, hull-similarity matrix); this figure is probe-only. Position is the only factor that flattens to chance at LOBO.](assets/fig_tldr_4b.png)</span>{#fig-tldr}</span>
<span id="cb3-353"><a href="#cb3-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-354"><a href="#cb3-354" aria-hidden="true" tabindex="-1"></a><span class="fu">## 64 Dimensions are enough for some properties</span></span>
<span id="cb3-355"><a href="#cb3-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-356"><a href="#cb3-356" aria-hidden="true" tabindex="-1"></a>We tested probe scores across different input sizes. We tested both direct increasing slices from the first dimensions ("native dims-0:K"), and increasing components of a PCA. Native dimensions require no extra computation. For rotation, scale, and count, the probe hits ~95% of its max performance by **64 dimensions**. Position is the only property that the *native* prefix can't recover at 256 dims (0.73 vs 0.90 raw) — a PCA at 256 components recovers it (0.91), so the signal is there, just not concentrated in the first 256 raw dims.</span>
<span id="cb3-357"><a href="#cb3-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-358"><a href="#cb3-358" aria-hidden="true" tabindex="-1"></a>This is a deployment-grade infrastructure win. **Storing a 64-D native prefix is a 16× index compression** that retains the geometric brain of the foundation model — for every property except chip-relative position, where you either keep the full 1024 or store a 256-D PCA basis alongside.</span>
<span id="cb3-359"><a href="#cb3-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-360"><a href="#cb3-360" aria-hidden="true" tabindex="-1"></a><span class="al">![Probe score vs input dimensionality — native dims-0:K tracks raw 1024 closely for rotation, scale, and count. Position is the only property where native-prefix-256 lags raw 1024; a PCA-256 recovers it.](assets/fig_dims_4b.png)</span>{#fig-dims}</span>
<span id="cb3-361"><a href="#cb3-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-362"><a href="#cb3-362" aria-hidden="true" tabindex="-1"></a>| Probe | dims-0:16 | dims-0:64 | dims-0:256 | PCA-16 | PCA-64 | PCA-256 | raw 1024 |</span>
<span id="cb3-363"><a href="#cb3-363" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|---|---|---|</span>
<span id="cb3-364"><a href="#cb3-364" aria-hidden="true" tabindex="-1"></a>| Rotation 4-cls | 0.72 | 0.86 | 0.90 | 0.59 | 0.89 | 0.93 | **0.94** |</span>
<span id="cb3-365"><a href="#cb3-365" aria-hidden="true" tabindex="-1"></a>| Scale R² | 0.94 | 0.99 | 0.997 | 0.97 | 0.997 | 0.998 | **0.998** |</span>
<span id="cb3-366"><a href="#cb3-366" aria-hidden="true" tabindex="-1"></a>| Count R² | 0.81 | 0.98 | 0.993 | 0.92 | 0.994 | 0.996 | **0.996** |</span>
<span id="cb3-367"><a href="#cb3-367" aria-hidden="true" tabindex="-1"></a>| Position 9-cls | 0.21 | 0.53 | 0.73 | 0.14 | 0.73 | 0.91 | **0.90** |</span>
<span id="cb3-368"><a href="#cb3-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-369"><a href="#cb3-369" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Operational Playbook</span></span>
<span id="cb3-370"><a href="#cb3-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-371"><a href="#cb3-371" aria-hidden="true" tabindex="-1"></a>How do you deploy this at planet scale?</span>
<span id="cb3-372"><a href="#cb3-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-373"><a href="#cb3-373" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Index Once.** Precompute Clay v1.5 embeddings for your entire corpus, or use our <span class="co">[</span><span class="ot">Lgnd API</span><span class="co">](https://lgnd.ai/lgnd-api)</span>.</span>
<span id="cb3-374"><a href="#cb3-374" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Train the Probe per Question.** Label enough chips per question to create linear probes and test how well they generalize, and how many dimensions are needed. Then query your corpus. If you are interested in upcoming LGND tooling to facilitate this, <span class="co">[</span><span class="ot">let us know</span><span class="co">](https://lgnd.ai/contact)</span>.</span>
<span id="cb3-375"><a href="#cb3-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-376"><a href="#cb3-376" aria-hidden="true" tabindex="-1"></a>**Three places linear probes change the agent's job.**</span>
<span id="cb3-377"><a href="#cb3-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-378"><a href="#cb3-378" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**First-pass filter.** *"Find chips with at least 3 boats"* becomes a single filter on the count column. The agent never sees the 99% of the corpus where N=0,1,2.</span>
<span id="cb3-379"><a href="#cb3-379" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Retrieval cue.** *"Tanker pointed roughly towards port"* becomes the conjunction of three probe-column filters (<span class="in">`is_boat = 1`</span>, <span class="in">`rotation e.g. 180° ± 45°`</span>, <span class="in">`near_refinery_POI = 1`</span>) plus a final agent verification step on the surviving few.</span>
<span id="cb3-380"><a href="#cb3-380" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Reranker (the binding case).** Cosine retrieval cannot distinguish *boat-north / vehicle-south* from *vehicle-north / boat-south*. A linear probe on the same vector hits 0.87. For change-detection workflows specifically, this is the deployment story: pre/post comparisons of the same scene across time will produce embeddings that are nearly identical to cosine *even when the compositional content has changed*. A probe trained on "is this configuration A or configuration B?" is the rerank instrument that converts the cosine null into an actionable signal.</span>
<span id="cb3-381"><a href="#cb3-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-382"><a href="#cb3-382" aria-hidden="true" tabindex="-1"></a>**Where the probe runs out.** Per-instance addressing — *"which of the N boats is the tanker?"*, pixel-precise polygons for damage assessment, attributing a property to a *specific* instance among multiple — is not in the CLS at all. Position is recoverable per-hull but does not transfer linearly to held-out hulls. Cross-scale and cross-vessel-class generalisation are partial. For those, a rough filter with the linear probes might help filter out clear cases, but the agent has to do the work — patch tokens with attention, SAM, Mask-RCNN, or full agentic reasoning over the chip pixels. The probe is the cheap layer that decides *whether* the agent has to, enabling much more efficient compute budget allocation.</span>
<span id="cb3-383"><a href="#cb3-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-384"><a href="#cb3-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-385"><a href="#cb3-385" aria-hidden="true" tabindex="-1"></a><span class="fu">## Appendix: Methods &amp; Caveats</span></span>
<span id="cb3-386"><a href="#cb3-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-387"><a href="#cb3-387" aria-hidden="true" tabindex="-1"></a><span class="fu">### LOBO spread</span></span>
<span id="cb3-388"><a href="#cb3-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-389"><a href="#cb3-389" aria-hidden="true" tabindex="-1"></a>We don't report means without spreads. Our **n=8 hand-digitized hulls** let us see the failure modes. Rotation accuracy 0.76 is a mean; the per-hull strip plot below shows boat_07 tanks to 0.30. The spread is the signal: a deployment that depends on per-chip guarantees should add a confidence column and route low-confidence cases to a heavier instrument.</span>
<span id="cb3-390"><a href="#cb3-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-391"><a href="#cb3-391" aria-hidden="true" tabindex="-1"></a><span class="al">![LOBO per-hull spread for all 5 probes. Each dot is one of the 8 held-out hulls; the dashed line is the LOBO mean. Rotation 4-cls and count R² have visible per-hull tails (boat_07 / boat_1+2+8). Scale R² is uniformly tight. Position is uniformly weak (~chance 0.111 for all hulls).](assets/fig_lobo_strip_4b.png)</span>{#fig-lobo-strip}</span>
<span id="cb3-392"><a href="#cb3-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-393"><a href="#cb3-393" aria-hidden="true" tabindex="-1"></a><span class="fu">### Per-(probe × hull) matrix — where cosine and probe disagree per hull</span></span>
<span id="cb3-394"><a href="#cb3-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-395"><a href="#cb3-395" aria-hidden="true" tabindex="-1"></a>The bar chart in §<span class="co">[</span><span class="ot">TL;DR</span><span class="co">](#tldr-the-findings-grouped-by-value)</span> gives a probe-level mean. Per-hull, the means hide reversals — most importantly **boat_07 rotation 4-cls**, where cosine top-5 NN (0.52) actually *beats* the linear probe (0.30) because the trained probe overfits to the 7-hull pool while cosine retrieval doesn't fit a hyperplane. That's an argument for **hull-distance-conditional routing**: cosine-NN if the query embedding is far from the training pool, probe if it's near.</span>
<span id="cb3-396"><a href="#cb3-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-397"><a href="#cb3-397" aria-hidden="true" tabindex="-1"></a><span class="al">![Per-(probe × held-out hull) matrix of LOBO scores. Left: cosine top-5 NN. Right: linear probe. Same 1024-D CLS, same split, two readouts. Rotation rows: probe matrix is uniformly greener (probe lifts every hull) *except* boat_07. Scale and count rows: cosine matrix matches or beats probe per hull. Position rows: both fail at LOBO.](assets/fig_cos_vs_probe_matrix_4b.png)</span>{#fig-cos-vs-probe-matrix}</span>
<span id="cb3-398"><a href="#cb3-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-399"><a href="#cb3-399" aria-hidden="true" tabindex="-1"></a><span class="fu">### How Distinct Are the 8 Hulls Really?</span></span>
<span id="cb3-400"><a href="#cb3-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-401"><a href="#cb3-401" aria-hidden="true" tabindex="-1"></a>We only tested here the case of ship hulls, and only 8 of them. We do not yet know how well these results will generalize to other classes of semantics (buildings, roads, agriculture, ... ) or properties (damaged, flooded, ... ). But we can at least check how distinct these 8 hulls are in embedding space. The mean off-diagonal cosine is 0.975 (range <span class="co">[</span><span class="ot">0.956, 0.990</span><span class="co">]</span>) — they're geometrically distinct but live in a tight neighbourhood of the embedding manifold. Read every LOBO number below as "generalisation within this neighbourhood", not "generalisation across semantics or even vessel families".</span>
<span id="cb3-402"><a href="#cb3-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-403"><a href="#cb3-403" aria-hidden="true" tabindex="-1"></a>!<span class="co">[</span><span class="ot">Cosine similarity matrix on the 8 canonical hull embeddings (centered on water, rotation 0°, scale 0.25). Off-diagonal mean 0.975 (range [0.956, 0.990]). The hulls are geometrically distinct but live in a tight neighbourhood of the embedding manifold — every LOBO number is generalisation *within this neighbourhood*, not across vessel families.</span><span class="co">](assets/fig_hullsim_4b.png)</span>{#fig-hullsim}</span>
<span id="cb3-404"><a href="#cb3-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-405"><a href="#cb3-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-406"><a href="#cb3-406" aria-hidden="true" tabindex="-1"></a><span class="fu">### Detailed Stats Table</span></span>
<span id="cb3-407"><a href="#cb3-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-408"><a href="#cb3-408" aria-hidden="true" tabindex="-1"></a>| Probe | Within-object (5-fold) | LOBO (8-hull mean) | Chance |</span>
<span id="cb3-409"><a href="#cb3-409" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|</span>
<span id="cb3-410"><a href="#cb3-410" aria-hidden="true" tabindex="-1"></a>| Rotation 4-cls (N/E/S/W) | 0.94 | 0.76 <span class="co">[</span><span class="ot">0.60, 0.90</span><span class="co">]</span> | 0.25 |</span>
<span id="cb3-411"><a href="#cb3-411" aria-hidden="true" tabindex="-1"></a>| Rotation 8-bin (cardinal+oblique) | 0.93 | 0.80 <span class="co">[</span><span class="ot">0.71, 0.88</span><span class="co">]</span> | 0.125 |</span>
<span id="cb3-412"><a href="#cb3-412" aria-hidden="true" tabindex="-1"></a>| Rotation continuous (sin/cos Ridge) | 17.8° MAE | 39.5° MAE | 90° MAE |</span>
<span id="cb3-413"><a href="#cb3-413" aria-hidden="true" tabindex="-1"></a>| Scale R² (5 levels) | 0.998 | 0.94 <span class="co">[</span><span class="ot">0.89, 0.98</span><span class="co">]</span> | 0.00 |</span>
<span id="cb3-414"><a href="#cb3-414" aria-hidden="true" tabindex="-1"></a>| Count R² (single hull) | 0.996 | 0.84 <span class="co">[</span><span class="ot">0.73, 0.96</span><span class="co">]</span> | 0.00 |</span>
<span id="cb3-415"><a href="#cb3-415" aria-hidden="true" tabindex="-1"></a>| Count R² (mixed hulls) | 0.92 | — *(no LOBO design)* | 0.00 |</span>
<span id="cb3-416"><a href="#cb3-416" aria-hidden="true" tabindex="-1"></a>| Position 9-cls @ scale 0.25 | 0.89 | 0.24 <span class="co">[</span><span class="ot">0.20, 0.29</span><span class="co">]</span> | 0.111 |</span>
<span id="cb3-417"><a href="#cb3-417" aria-hidden="true" tabindex="-1"></a>| Binding probe ("boat1 at top?") | 0.87 (perm-p&lt;0.005) | — | 0.50 |</span>
<span id="cb3-418"><a href="#cb3-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-419"><a href="#cb3-419" aria-hidden="true" tabindex="-1"></a>LOBO numbers are mean ± 95% bootstrap CI across the 8 held-out hulls (2,000 resamples each). 5-fold numbers are mean across folds of 80/20 train/test splits (same hulls in train and test).</span>
<span id="cb3-420"><a href="#cb3-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-421"><a href="#cb3-421" aria-hidden="true" tabindex="-1"></a><span class="fu">### Reproduce</span></span>
<span id="cb3-422"><a href="#cb3-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-423"><a href="#cb3-423" aria-hidden="true" tabindex="-1"></a>All the post's compute lives in **two files**: <span class="in">`pipeline.py`</span> (715 lines — compose → embed → probe → binding → polygon → ELLE → clipping → widget) and <span class="in">`figures.py`</span> (478 lines — every figure in the post). Each is a thin CLI over a self-contained module. Code in the <span class="co">[</span><span class="ot">devlogs repo</span><span class="co">](https://github.com/EarthLegend/devlogs)</span>.</span>
<span id="cb3-424"><a href="#cb3-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-425"><a href="#cb3-425" aria-hidden="true" tabindex="-1"></a>The encoder is the public <span class="co">[</span><span class="ot">Clay foundation model</span><span class="co">](https://github.com/Clay-foundation/model)</span> — NAIP is a native Clay collection, so the encoder + band metadata + datacube helpers all ship there. Outside the encoder, the pipeline is plain PyTorch + NumPy + scikit-learn (Ridge, LinearSVC, KFold) — nothing exotic.</span>
<span id="cb3-426"><a href="#cb3-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-427"><a href="#cb3-427" aria-hidden="true" tabindex="-1"></a>**Get the Clay v1.5 encoder weights** (~1.2 GB, extracted from the public 5 GB checkpoint):</span>
<span id="cb3-428"><a href="#cb3-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-429"><a href="#cb3-429" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-430"><a href="#cb3-430" aria-hidden="true" tabindex="-1"></a><span class="in"># Download clay-v1.5.ckpt from https://huggingface.co/made-with-clay/Clay (file: v1.5/clay-v1.5.ckpt)</span></span>
<span id="cb3-431"><a href="#cb3-431" aria-hidden="true" tabindex="-1"></a><span class="in">export CLAY_CKPT=/path/to/clay-v1.5.ckpt</span></span>
<span id="cb3-432"><a href="#cb3-432" aria-hidden="true" tabindex="-1"></a><span class="in">export CLAY_ENCODER_PT="$PWD/clay-v1.5_encoder.pt"</span></span>
<span id="cb3-433"><a href="#cb3-433" aria-hidden="true" tabindex="-1"></a><span class="in">python stream_extract_encoder.py     # streams the ZIP-checkpoint without loading 5 GB into RAM</span></span>
<span id="cb3-434"><a href="#cb3-434" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-435"><a href="#cb3-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-436"><a href="#cb3-436" aria-hidden="true" tabindex="-1"></a>The ELLE step (<span class="in">`pipeline.py elle`</span>) additionally needs a <span class="in">`clay_naip_pairs.pt`</span> file with paired (CLS-embedding, reconstruction-loss) tensors for a few thousand NAIP chips — same artefact described in our companion <span class="co">[</span><span class="ot">ELLE devlog</span><span class="co">](../2026-03-01-self-aware-embeddings/)</span>, which has the recipe to generate it. You can skip the ELLE step and still run every other command.</span>
<span id="cb3-437"><a href="#cb3-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-438"><a href="#cb3-438" aria-hidden="true" tabindex="-1"></a>**Run.**</span>
<span id="cb3-439"><a href="#cb3-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-440"><a href="#cb3-440" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-441"><a href="#cb3-441" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py compose          # 1,042 4-band composite chips from canonicals</span></span>
<span id="cb3-442"><a href="#cb3-442" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py embed 9999       # full Clay v1.5 embedding pass (resumable; embed [SECS] is a wall-clock budget, default 40 s for sandboxed reruns — pass a large value to finish in one shot)</span></span>
<span id="cb3-443"><a href="#cb3-443" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py probes           # within + LOBO + rotcont + hullsim + bootstrap</span></span>
<span id="cb3-444"><a href="#cb3-444" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py binding          # boat1↔boat2 swap test (re-embeds 96 chips internally)</span></span>
<span id="cb3-445"><a href="#cb3-445" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py polygon          # polygon-from-CLS soft-IoU + specific-boat</span></span>
<span id="cb3-446"><a href="#cb3-446" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py cosvsprobe       # cosine top-5 NN vs linear probe under LOBO</span></span>
<span id="cb3-447"><a href="#cb3-447" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py dims             # dims-0:K vs PCA-K vs raw 1024</span></span>
<span id="cb3-448"><a href="#cb3-448" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py elle             # ELLE manifold gauge + per-hull confidence (needs clay_naip_pairs.pt — see above)</span></span>
<span id="cb3-449"><a href="#cb3-449" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py clipping         # alpha-overflow audit</span></span>
<span id="cb3-450"><a href="#cb3-450" aria-hidden="true" tabindex="-1"></a><span class="in">python pipeline.py widget 9999      # boat_06 cross-product widget data (same SECS-budget pattern as embed)</span></span>
<span id="cb3-451"><a href="#cb3-451" aria-hidden="true" tabindex="-1"></a><span class="in">python figures.py all               # render all 17 figures</span></span>
<span id="cb3-452"><a href="#cb3-452" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-453"><a href="#cb3-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-454"><a href="#cb3-454" aria-hidden="true" tabindex="-1"></a><span class="in">`pipeline.py all`</span> runs every step in order with default wall-clock budgets, which is convenient for resumable reruns but **does not finish a fresh embed pass** (the default <span class="in">`embed`</span> budget is 40 s) — on first run, call <span class="in">`embed 9999`</span> separately, then <span class="in">`all`</span>.</span>
<span id="cb3-455"><a href="#cb3-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-456"><a href="#cb3-456" aria-hidden="true" tabindex="-1"></a>The Clay v1.5 encoder forward pass is single-CPU friendly (no GPU required); <span class="in">`embed`</span> is the long pole and runs in tens of minutes on a laptop. Every other step is seconds-to-a-minute. Both <span class="in">`embed`</span> and <span class="in">`widget`</span> write resumable state, so re-running picks up where it left off.</span>
<span id="cb3-457"><a href="#cb3-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-458"><a href="#cb3-458" aria-hidden="true" tabindex="-1"></a>Three one-off setup helpers stay separate from the main pipeline: <span class="in">`stream_extract_encoder.py`</span> (covered above), <span class="in">`polygons_wide_to_canonicals.py`</span> (QGIS polygon → 4-band canonical extraction), and <span class="in">`fetch_wide_4band_tiff.py`</span> (raw NAIP TIFF fetching from MPC). The latter two only matter if you want to rebuild the canonical hulls and water tile from scratch — the <span class="in">`assets/`</span> directory in the repo already ships them.</span>
<span id="cb3-459"><a href="#cb3-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-460"><a href="#cb3-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-461"><a href="#cb3-461" aria-hidden="true" tabindex="-1"></a><span class="fu">## Prior Art {#prior-art}</span></span>
<span id="cb3-462"><a href="#cb3-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-463"><a href="#cb3-463" aria-hidden="true" tabindex="-1"></a>*Backbone, EO foundation-model siblings.*</span>
<span id="cb3-464"><a href="#cb3-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-465"><a href="#cb3-465" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**He et al. 2022** — *[Masked Autoencoders Are Scalable Vision Learners](https://arxiv.org/abs/2111.06377)* (CVPR 2022). The backbone of Clay v1.5. Pixel reconstruction at absolute positions is the most parsimonious explanation for geometric axes surviving the single-CLS readout.</span>
<span id="cb3-466"><a href="#cb3-466" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Cong et al. 2022** — *[SatMAE: Pre-training Transformers for Temporal and Multi-Spectral Satellite Imagery](https://arxiv.org/abs/2207.08051)* (NeurIPS 2022). Linear-probe transfer evaluation is the standard discipline in EO foundation-model benchmarks. This work extends that discipline from classification-task transfer into a controlled multi-factor probe sweep on a single scene.</span>
<span id="cb3-467"><a href="#cb3-467" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Brown et al. 2025** — *[AlphaEarth Foundations: An embedding field model for accurate and efficient global mapping from sparse label data](https://arxiv.org/abs/2507.22291)* (DeepMind). A direct sibling on the pre-indexed-embeddings-at-planet-scale architectural pattern: AEF ships annual 64-D embeddings per 10 m pixel; LGND ships per-chip 1024-D Clay embeddings across NAIP, S2, Landsat. Same wedge — embed once at index time, query many times after — measured here at the chip level for a different sensor stack.</span>
<span id="cb3-468"><a href="#cb3-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-469"><a href="#cb3-469" aria-hidden="true" tabindex="-1"></a>*Probing as methodology.*</span>
<span id="cb3-470"><a href="#cb3-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-471"><a href="#cb3-471" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Alain &amp; Bengio 2016** — *[Understanding intermediate layers using linear classifier probes](https://arxiv.org/abs/1610.01644).* The foundational paper for probing-as-methodology. Every linear-probe number in this post stands on the discipline this paper established: train a fresh classifier on frozen features, read off what's linearly recoverable.</span>
<span id="cb3-472"><a href="#cb3-472" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Hewitt &amp; Manning 2019** — *[A Structural Probe for Finding Syntax in Word Representations](https://aclanthology.org/N19-1419/)* (NAACL 2019). Showed entire syntax trees are linearly recoverable from BERT/ELMo geometry. Our finding is the EO analogue: geometric factors (rotation, count, size, content×position binding) are linearly recoverable from Clay's CLS.</span>
<span id="cb3-473"><a href="#cb3-473" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Kim et al. 2018** — *[Quantitative Testing with Concept Activation Vectors (TCAV)](https://arxiv.org/abs/1711.11279)* (ICML 2018). Our probes are TCAV applied to satellite imagery — concept activation vectors trained on a controlled stimulus set, validated by the held-out generalization (LOBO) we report here.</span>
<span id="cb3-474"><a href="#cb3-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-475"><a href="#cb3-475" aria-hidden="true" tabindex="-1"></a>*CLS geometry, anisotropy, register artefacts.*</span>
<span id="cb3-476"><a href="#cb3-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-477"><a href="#cb3-477" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Ethayarajh 2019** — *[How Contextual are Contextualized Word Representations?](https://arxiv.org/abs/1909.00512)* (EMNLP 2019). The underlying reason ViT CLS cosines saturate near 1.0 — and why our binding test recovers the signal via a probe but not via cosine.</span>
<span id="cb3-478"><a href="#cb3-478" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Darcet et al. 2024** — *[Vision Transformers Need Registers](https://arxiv.org/abs/2309.16588)* (ICLR 2024). CLS-token artefacts matter for chip-level probes like ours; a register-equipped Clay variant would be a cleaner canvas for the position-fails-at-LOBO finding specifically.</span>
<span id="cb3-479"><a href="#cb3-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-480"><a href="#cb3-480" aria-hidden="true" tabindex="-1"></a>*Compositional binding, counting, disentanglement.*</span>
<span id="cb3-481"><a href="#cb3-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-482"><a href="#cb3-482" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Yuksekgonul et al. 2023** — *[When and Why Vision-Language Models Behave like Bags-of-Words](https://arxiv.org/abs/2210.01936)* (ICLR 2023, oral). The canonical compositional-binding-failure result for VLMs: CLIP fails the ARO benchmark for attribute binding and word order. Our binding test is the EO foundation-model instantiation — same finding (cosine retrieval cannot deliver compositional binding), different stimulus class, controlled to two real hulls + a noise floor + a 200-permutation test.</span>
<span id="cb3-483"><a href="#cb3-483" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Paiss, Chefer, Wolf 2023** — *[Teaching CLIP to Count to Ten](https://arxiv.org/abs/2302.12066)* (ICCV 2023). CLIP needed explicit counting supervision. Clay's R² ≈ 0.99 within-object (0.84 LOBO) with no language supervision is a (modest) data point for the MAE-reconstruction-teaches-counting side.</span>
<span id="cb3-484"><a href="#cb3-484" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Locatello et al. 2019** — *[Challenging Common Assumptions in the Unsupervised Learning of Disentangled Representations](https://arxiv.org/abs/1811.12359)* (ICML 2019, best paper). Disentanglement-as-a-frame is contested: without inductive biases, well-disentangled models cannot be identified without supervision. We don't claim factor disentanglement here — we claim factor *recoverability* via supervised linear probes, which is the weaker, identifiable claim.</span>
<span id="cb3-485"><a href="#cb3-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-486"><a href="#cb3-486" aria-hidden="true" tabindex="-1"></a>*Dimensionality reduction critique.*</span>
<span id="cb3-487"><a href="#cb3-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-488"><a href="#cb3-488" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Chari &amp; Pachter 2023** — *[The Specious Art of Single-Cell Genomics](https://doi.org/10.1371/journal.pcbi.1011288)* (PLOS Computational Biology). Their argument is that UMAP/t-SNE *fabricate* structure. Our finding is different — we show UMAP *loses* count and is indistinguishable from PCA-2 on the rest. Same concern, different symptom.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© LGND AI · Posts are <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a> · Code is <a href="https://opensource.org/licenses/MIT">MIT</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/EarthLegend/devlogs/edit/main/posts/2026-04-22-geometric-probing-clay/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/EarthLegend/devlogs/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>